### PR TITLE
feat: make setComponent and dependency properties and methods public

### PR DESCRIPTION
**Pull request by proempire**
# Description

This PR wants to solve this issue by making setComponent public, then we can override the behavior of setComponent, decide whether to make the tab focused or not.

## Motivation & context

Sometimes we need one tab automatically switch to another tab without being focused (i.e., A carousel with auto-scroll feature). In current design, we can't override the focus behavior because it's encapsulated in tabs.ts setComponent.

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [ ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [x] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by SethDonohue — APPROVED** [review]

**Comment by chrisdholt** [comment]
What are the accessibility implications supporting this behavior?

**Comment by SethDonohue** [comment]
After further discussion I have reset my review. There is likely a better and potentially faster way to use Tabs to be able to access these methods for use and control on other components that extend it. One being  _forking_ Tabs, making any changes needed that way, and bringing those changes over to the component that is extending/using Tabs.

**Review by chrisdholt — CHANGES_REQUESTED** [review]
Thanks for the PR @proempire - I'm happy to learn a bit more about the goals here but I'm not sure that making everything which is currently private set to public is the right move here. While I get that in a carousel implementation of Tabs one might want to auto-rotate and *not* focus the control, I think that if Carousel existed with this behavior, the value of making this public would be greatly diminished. If there are more use cases where having focus and selection be separate, I think we could consider making this change - even then, I think we'd want to look at what the right public API is and how that affects the internal controls. As it currently stands, this seems to just make everything private public so it can be changed and I don't think that's necessarily the right path forward. I think we'd want a more condensed and clear public API.

**Comment by SethDonohue** [comment]
Closing as this is no longer needed.

**Pull request closed without merging**
