### PR TITLE
chore: attempt to update server settings to allow for local testing of sites in iframes

### PR DESCRIPTION
**Pull request by janechu**
# Description

This allows sites to be referred to from a localhost environment.

## Motivation & context

This should help with testing sites in iframes when used in localhost.

## Issue type checklist

- [x] **Chore**: A change that does not impact distributed packages.
- [ ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by awentzel — CHANGES_REQUESTED** [review]
This was previously set and found to be a security violation so I removed it.  However, I didn't try setting a single attribute.  

Rather, than let this PR go in and then have to revert, we can try this out on the creator staging site if you want?  I can update directly on the server and then rescan, if it works great, we can let this change go in.  If not, then we should find a secure solution.

**Comment by janechu** [comment]
@awentzel that would be great!

**Comment by awentzel** [comment]
> @awentzel that would be great!

Please try testing on https://stage.create.fast.design which now has your code implemented directly.  Thanks

**Comment by awentzel** [comment]
Resolved by #4572 after manually testing.

**Pull request closed without merging**
