### PR TITLE
fix: change style Attribute to style tag(to add CSP support)

### PR DESCRIPTION
**Pull request by SilkyFowl**
# Pull Request

## 📖 Description

This PR is to make it possible to set nonce for fast-element.
This solved the problem I encountered, but I couldn't decide if this policy is OK, so I made a Draft.
I hope this helps with #5444.

### Background

This all started when I realized that it was hard to resolve a csp violation in my repository.

https://github.com/SilkyFowl/fable-vscode-extension-samples/pull/17

The [@vscode/webview-ui-toolkit](https://github.com/microsoft/vscode-webview-ui-toolkit) used in this repository depends on fast.
By the way, vscode extension [recommends the use of Content security policy when using WebView.](https://code.visualstudio.com/api/extension-guides/webview#content-security-policy)
A sample implementation can be found here.
https://github.com/microsoft/vscode-extension-samples/blob/e958fb7d45abda8177f413062318447ce59c780f/webview-sample/src/extension.ts#L196

Currently, if using Vscode's webview-ui-toolkit, it will violate Vscode's recommendations.
To resolve the inconsistency of webview-ui-toolkit, we need to resolving #5444.

### 🎫 Issues

#5444 <- #4510

This PR was created using #5444 as a hint.

### General

- [ ] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
I do have some concerns over the performance of running the query selector on every view, particularly since we don't tend to put style tags in our templates. We prefer to handles styles with the `css` tagged template handler. So, I think there is probably a better way for us to handle this. @nicholasrice may have some thoughts on that.

**Comment by SilkyFowl** [comment]
Thanks for the review.
I'm embarrassed to say that I overlooked the performance degradation caused by query selector.

> @nicholasrice may have some thoughts on that.

Should I wait for him to formulate his thoughts?

**Comment by EisenbergEffect** [comment]
@SilkyFowl No need to be embarrassed. It's a pragmatic solution that looks like it would address the issue. I happen to be very, very familiar with this part of the code and all the implications, so it jumps out to me more than most.

I'd like to wait to hear some thoughts from @nicholasrice since he's done some investigation in this area and we were tracking some improvements to FE 2 for this. With holiday season coming up, it might be a little bit longer than normal for him to get around to it though.

**Comment by SilkyFowl** [comment]
@EisenbergEffect Thank you very much.
If it takes a little time, does that mean I should Close this PR?
If improvements are to be made based on @nicholasrice's findings, then a new PR with that policy will be created, right?
In that case, I'll comment on #5444 if I notice anything.

**Comment by EisenbergEffect** [comment]
@SilkyFowl Yes, I think that would be the best course for now. If you can share your specific scenarios in #5444 then we can all use that issue to discuss together the optimal solution. Once we've arrived at a place we all agree on, then if you would like to contribute through code, we'd love to have you work together with us on a new PR. But I think we should start with a discussion in the issue and also make sure that Nick has a chance to weigh in.

**Comment by EisenbergEffect** [comment]
I'll close this PR in favor of the issue discussion for now.

**Pull request closed without merging**
