### PR TITLE
remove algolia from docusaurus

### PR DESCRIPTION
**Pull request by chrisdholt**
# Pull Request

## 📖 Description
Removes algolia from docusaurus

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
I don't remember how this is all configured, but it might be worth checking that there isn't more configuration that needs to be changed to disable search. This will definitely make the search not work anymore, but I'm not sure if it will remove the search from the header.

Is there a reason to remove search?

**Comment by chrisdholt** [comment]
> I don't remember how this is all configured, but it might be worth checking that there isn't more configuration that needs to be changed to disable search. This will definitely make the search not work anymore, but I'm not sure if it will remove the search from the header.
> 
> Is there a reason to remove search?

It's a mitigation in code to get the issue resolved - we aren't currently releasing docs so this technically won't break the site until the next release. My hope is to get this sorted and add back in with proper deployments.

**Review by EisenbergEffect — APPROVED** [review]

**Review by KingOfTac — APPROVED** [review]

**Comment by awentzel** [comment]
I recommend creating a new PR in the future to retain the API information otherwise, whoever implements this feature has to start from scratch. The solution was pretty simple. https://www.algolia.com/doc/api-reference/api-methods/generate-secured-api-key/

**Comment by chrisdholt** [comment]
> I recommend creating a new PR in the future to retain the API information otherwise, whoever implements this feature has to start from scratch. The solution was pretty simple. https://www.algolia.com/doc/api-reference/api-methods/generate-secured-api-key/ I'll create an issue to resolve this.

We need to recycle the key as bad actors can still pull it from history potentially. We're tracking this and getting the build squared as a priority. Thx!

**Comment by awentzel** [comment]
> > I recommend creating a new PR in the future to retain the API information otherwise, whoever implements this feature has to start from scratch. The solution was pretty simple. https://www.algolia.com/doc/api-reference/api-methods/generate-secured-api-key/ I'll create an issue to resolve this.
> 
> We need to recycle the key as bad actors can still pull it from history potentially. We're tracking this and getting the build squared as a priority. Thx!

new issue: https://github.com/microsoft/fast/issues/6895

**Pull request merged**
