### PR TITLE
chore: add codeQL to ci-weekly

### PR DESCRIPTION
**Pull request by Ibrahimmaga**
Discover vulnerabilities across a codebase with 
# Description
ci-weekly.yml previously included a code section for code quality analysis. This seems to have been removed and requires adding back in.

- name: Initialize CodeQL
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
      uses: github/codeql-action/init@v1
      with:
        languages: javascript, typescript, csharp

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
    There is a if condition. this will execute codeQL only if there is a push to master, and not on schedule trigger.
## Motivation & context
discover a bad pattern and then find similar occurrences across the entire codebase

https://github.com/microsoft/fast/issues/4405
## Issue type checklist

- [x] **Chore**: A change that does not impact distributed packages.
- [ ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [x] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by awentzel — COMMENTED** [review]
This only needs to run one time on one platform, preferably the fastest pipeline.

**Comment by Ibrahimmaga** [comment]
we can make it run on linux

**Review by awentzel — CHANGES_REQUESTED** [review]
This looks like a merge failure.  I would expect only a couple files not 39 in this branch.  To understand how merging vs rebasing works, please read https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by Ibrahimmaga** [comment]
this PR needs to be close due to much conflicts. Another PR will be created to resolve the issue.

**Pull request closed without merging**
