### PR TITLE
remove noImplicitAny in fast-element

### PR DESCRIPTION
**Pull request by m4thieulavoie**
# Pull Request

## 📖 Description

This PR removes the `noImplicitAny` flag in `fast-element` `tsconfig` file. I purposely left some declarations as either `any` or `unknown`, but definitely feel free to propose a cleaner typing 👍 

### 🎫 Issues

https://github.com/microsoft/fast/issues/5337

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@m4thieulavoie I'm going to close this PR as it would create a bunch of conflicts with the work being done on FASTElement 2.0, where there are a good number of internal changes already made. If you would like to open a PR against that branch, I'd be happy to accept that.

**Comment by m4thieulavoie** [comment]
> @m4thieulavoie I'm going to close this PR as it would create a bunch of conflicts with the work being done on FASTElement 2.0, where there are a good number of internal changes already made. If you would like to open a PR against that branch, I'd be happy to accept that.

Sounds good, I'll update all my PRs to reflect this 👍

**Comment by m4thieulavoie** [comment]
@chrisdholt I'm a bit confused by the state of `fast-element`. https://github.com/microsoft/fast/pull/5303 doesn't seem to have made its way through the fast-element-2 branch. Should I wait to tackle https://github.com/microsoft/fast/issues/5337 ?

**Comment by EisenbergEffect** [comment]
The fast-element 2 branch is going to ignore everything in #5303 and just reimplement the fixes, since there aren't that many. It was a compromise.

**Pull request closed without merging**
