### PR TITLE
Added watch script and chokidar

### PR DESCRIPTION
**Pull request by janechu**
# Pull Request

## 📖 Description

This PR adds `chokidar` so that we can watch files and re-run the playwright tests. Playwright does not currently have a watcher for this purpose so `chokidar-cli` was added to facilitate this.

### General

- [ ] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Comment by janechu** [comment]
So, I ran `yarn workspace @microsoft/fast-ssr add chokidar-cli --dev` and all these changes to the yarn lockfile showed up.

**Comment by EisenbergEffect** [comment]
> So, I ran `yarn workspace @microsoft/fast-ssr add chokidar-cli --dev` and all these changes to the yarn lockfile showed up. Not terribly sure if that's an issue.

How do we want to handle lockfile scenarios in a long running feature branch like this?

**Comment by janechu** [comment]
> How do we want to handle lockfile scenarios in a long running feature branch like this?

Well, I'm not sure myself, I'd like to say as long as the build is passing it should mean that the changes that went in are benign. I can't think of a condition in which the build gate passes and that creates an issue downstream vis a vis our distributed packages.

**Comment by EisenbergEffect** [comment]
I think most of the build fails are due to things that need to be adjusted in foundation based on the changes I've made in fast-element. I was waiting on making changes there to not have merge conflicts with master for the foundation library. We might want to bite the bullet on that though.

**Review by EisenbergEffect — APPROVED** [review]

**Pull request merged**
