### PR TITLE
add lighthouse on CI

### PR DESCRIPTION
**Pull request by Ibrahimmaga**
# Pull Request

## 📖 Description
This change will add a lighthouse to CI such that we can monitor compliance and performance-related metrics. This is a minor step in the right direction and can be evolved further in the future.  

### 🎫 Issues
Feature Improvement not issue.

## 👩‍💻 Reviewer Notes
We should either approve, which I'm in favor of. OR disapprove and abandon as Ibrahim is no longer supporting the project.  But, I believe this is still of value to the project.

### General

- [ ] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Comment by awentzel** [comment]
@Ibrahimmaga, What is the status on this PR?

**Comment by Ibrahimmaga** [comment]
> @Ibrahimmaga, What is the status on this PR?

Let me run the CI and see what result we are getting

**Comment by Ibrahimmaga** [comment]
> @Ibrahimmaga, What is the status on this PR?

I like the tool, but the performance number doesn't add up when comparing to the lighthouse. sounds misleading. The only thing that matches is best practice and accessibility
image
image

**Comment by awentzel** [comment]
@Ibrahimmaga,

> I like the tool, but the performance number doesn't add up when comparing to the lighthouse. sounds misleading. The only thing that matches is best practice and accessibility

The way I'm interpreting this behavior is by design.  I imagine there are different metrics to test on mobile vs desktop. For example, in mobile-first scenarios, much of the UI will not be generated to improve performance and simplify the user experience.  In a desktop scenario, there is much more real estate to work with and so the UI often encompasses everything..  There are differences by design.

Have you filed an issue on the GitHub Action project to get an explanation and understand what's going on and why this behavior is different?  I assume there is documentation or a way to reach the author to get answers?

**Comment by awentzel** [comment]
Status update.  We ran into an issue with the original GH Action we were to use.  We are now evaluating two other Actions to accomplish the same thing. We will continue to use this PR to test and determine which will work best with out environment.

**Comment by Ibrahimmaga** [comment]
> Status update. We ran into an issue with the original GH Action we were to use. We are now evaluating two other Actions to accomplish the same thing. We will continue to use this PR to test and determine which will work best with our environment.

When using another Github action, Numbers are a little better except the performance that is in the 20 %. when using lighthouse on google chrome, the performance is 89%.
image

**Review by awentzel — COMMENTED** [review]
This is better than what we offer today so It can probably be approved after adding the other sites we want to analyze.  

* www.fast.design
* explore.fast.design
* color.fast.design

Also, if there is a way to print the output summary to the console so it's apparent in the PR itself in addition to creating the link to click to review that would be great.

**Comment by awentzel** [comment]
> This is better than what we offer today so It can probably be approved after adding the other sites we want to analyze.
> 
> * [www.fast.design](http://www.fast.design)
> * explore.fast.design
> * color.fast.design
> 
> Also, if there is a way to print the output summary to the console so it's apparent in the PR itself in addition to creating the link to click to review that would be great.

The "other" sites is now a moot point, we primarily care about www.  I propose approving and pushing this in, then improving latest as needed.  Additionally, there are conversations about migrating from subdomain structure to subdirectories to reduce maintenance effort and cost.

**Review by awentzel — APPROVED** [review]

**Comment by EisenbergEffect** [comment]
Closing this for now. We can revisit again later.

**Pull request closed without merging**
