### PR TITLE
Remove @microsoft/fast-foundation and @microsoft/fast-web-utilities

### LINKED ISSUE #6951: RFC: Removal of `@microsoft/fast-foundation`
# Removal of `@microsoft/fast-foundation`

## Reason for removal

This package does not fill what FAST considers a core goal of the project. The FAST project seeks to provide useful tools for creating components as a platform gap filler, and not creating the components themselves. Refer to the [core goals in the project re-alignment issue](https://github.com/microsoft/fast/issues/6955).

It is noted that the package has proved to be useful and popular among consumers, so we're open to the adoption of the package by other interested parties.

### LINKED ISSUE #6954: Removal of `@microsoft/fast-web-utilities`
# Removal of `@microsoft/fast-web-utilities`

## Reason for removal

Once the other packages have been removed, this package has limited use as it was primarily for removing duplication.

### PR DESCRIPTION
**Pull request by janechu**
# Pull Request

## 📖 Description

This change removes:
- `@microsoft/fast-foundation` - the most recent version can be found on branch `archives/fast-foundation-3`
- `@microsoft/fast-web-utilities`

### 🎫 Issues

Closes #6951 and closes #6954

### General

- [ ] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://github.com/microsoft/fast/blob/master/CODE_OF_CONDUCT.md#our-standards) for this project.

## ⏭ Next Steps

- File an issue to remove dependency on `@microsoft/fast-foundation` in `@microsoft/fast-ssr` for testing.

### CODE REVIEW

**Review by chrisdholt — APPROVED** [review]

**Comment by radium-v** [comment]
Would it be possible to move `fast-element`, `fast-router`, and `fast-ssr` up one level to be directly in the `packages/` directory? They're currently in `packages/web-components/`.

**Comment by chrisdholt** [comment]
> Would it be possible to move `fast-element`, `fast-router`, and `fast-ssr` up one level to be directly in the `packages/` directory? They're currently in `packages/web-components/`.

I think this is a follow-up as part of the reorganization of the monorepo to npm workspaces (@janechu can correct me if I'm wrong)

**Comment by radium-v** [comment]
I'm getting an error when preparing and building from a clean state. I think `@microsoft/site-utilities` needs `"@microsoft/fast-element": "^2.0.0-beta.26",` in its dev dependencies.

**Comment by janechu** [comment]
> > Would it be possible to move `fast-element`, `fast-router`, and `fast-ssr` up one level to be directly in the `packages/` directory? They're currently in `packages/web-components/`.
> 
> I think this is a follow-up as part of the reorganization of the monorepo to npm workspaces (@janechu can correct me if I'm wrong)

The issue with moving files like that wholesale is you lose the git history or at least it becomes very hard to track because you have to go back to before the commit where you moved things. If we feel that's not a big deal we can move things up a folder, I didn't want to do it without some discussion.

**Review by radium-v — APPROVED** [review]

**Pull request merged**
