### PR TITLE
Components use html templates

### PR DESCRIPTION
**Pull request by m4thieulavoie**
# Pull Request

## 📖 Description

This PR adds extra typings by using the `html` template function in `fast-component`'s components parts.

Fixes https://github.com/microsoft/fast/issues/5349

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Review by radium-v — APPROVED** [review]

**Review by chrisdholt — APPROVED** [review]
Would love to get @eisenbergeffect to confirm approval here as there is a slight performance cost to using templates.

**Review by eljefe223 — APPROVED** [review]

**Comment by EisenbergEffect** [comment]
I'd like to propose an alternative. If the issue is primarily about typing, could we add a cast instead? There is a cost to making things templates, when they could be string. Perhaps switch these back to string but then cast the string as something like this:

```ts
export type TemplatePart = string | ViewTemplate;
```

Thoughts?

**Comment by radium-v** [comment]
@EisenbergEffect the types should already be `SyntheticViewTemplate | string` or something similar, which is what allows the properties to be strings or templates here (see this comment https://github.com/microsoft/fast/issues/5349#issuecomment-1004457459).

**Comment by EisenbergEffect** [comment]
So, is this more about wanting syntax highlighting then?

**Review by EisenbergEffect — CHANGES_REQUESTED** [review]
As much as I'd like to get syntax highlighting here, I'm not sure we should take this approach. The reason is that this has runtime consequences. Where we had strings before, we will now have to compile and create a FAST template instance. And every instance of any of these components will then have to dynamically instantiate that template and compose the views be default. The strings are much cheaper as they just get streamed into the static HTML of the parent template.

I thought there was a way with some of the VS Code plugins to indicate that a string was HTML without using a template tag. Could we leverage that in this case? If not, could we look into adding this as a feature of our own plugin? I think that would be a better approach because it would get us the design-time experience we want without costing us at runtime.

**Comment by radium-v** [comment]
> I thought there was a way with some of the VS Code plugins to indicate that a string was HTML without using a template tag. Could we leverage that in this case?

This would be difficult because there's no way to determine if an untagged template string is any sort of specific language. It would also need to support expressions within that subset.

One option would be to use build-time imports for these partials, where the template content is placed in a raw file with its appropriate extension. This would only work if the content of the string is pure markup - for example, SVG markup in a regular SVG file, injected in-place with a rollup plugin. This would only work for templates with no additional transformations, since template expressions (`${}`) would exhibit the same issue since most languages don't see expressions as a valid construct, and any common directives would exhibit the same non-deterministic behavior but in reverse.

Another would be to modify our syntax highlighting extension to allow something like this:

```ts
    indicator: /* html */ `
        <div part="indicator" class="indicator"></div>
    `,
```

This may work, but it could end up sending the wrong signals when we have ``html`<div></div>` `` and ``/* html */`<div></div>` `` throughout the project.

**Comment by EisenbergEffect** [comment]
Per an offline convo between myself and @radium-v we're going to look into enabling the comment syntax and see if we can leverage that here.

**Review by EisenbergEffect — APPROVED** [review]
Thanks for this follow-up!

**Pull request merged**
