### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gpresland**
# Description

- Correct _Github_ to _GitHub_.
- Remove trailing whitespaces.

## Motivation & context

Simply noticed wrong casing in the word _GitHub_ when reading README.

## Issue type checklist

- [x] **Chore**: A change that does not impact distributed packages.
- [ ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/en/contributing/standards) for this project.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@gpresland This seems like a meaningful fix. Was there any reason you decided to close the PR?

**Comment by gpresland** [comment]
@EisenbergEffect I noticed the casing differences afterwards also had an occurrence in the _CONTRIBUTING_ doc as well which should be have been added to this PR. Also, after glossing over the _CONTRIBUTING.md_ I was considering that this PR was perhaps too pedantic and insignificant to bother the fast team with. So for both those reason I figured I should just close it.

I could update the PR to include all instances across all markdown files and reopen it if it is a valuable enough contribution.

**Comment by EisenbergEffect** [comment]
@gpresland If you are willing, we'd love to have this as a contribution. To be frank, I'm a bit embarrassed that we managed to get the casing wrong. It's also incorrect on our web site 😢  If you want to re-open this and amend it with the other changes or just open up a new PR, we'll gladly accept the contribution. Let me know what you want to do. We're never bothered by willing community members who want to help make things better 😄

**Comment by gpresland** [comment]
@EisenbergEffect New PR created here: https://github.com/microsoft/fast/pull/3486.

**Comment by EisenbergEffect** [comment]
Awesome. Thanks @gpresland !

**Pull request closed without merging**
