### PR TITLE
docs fix (fast-element): Binding docs fix

### PR DESCRIPTION
**Pull request by tgoze**
# Pull Request

## 📖 Description

The documentation for the Observable API provides an incorrect example for how to use the Observable.binding() function. A correct implementation is provided.

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by EisenbergEffect — APPROVED** [review]

**Comment by EisenbergEffect** [comment]
Looks good. As I'm looking over this, I'm wondering if we can make an ergonomics improvement of having the `defaultExeuctionContext` be the default value of the `observe` function.  @tgoze Thoughts?

**Comment by tgoze** [comment]
> Looks good. As I'm looking over this, I'm wondering if we can make an ergonomics improvement of having the `defaultExeuctionContext` be the default value of the `observe` function. @tgoze Thoughts?

@EisenbergEffect I noticed that when using Observable.binding to listen to a volatile getter, the ExecutionContext is essentially ignored. Maybe make it an optional because it isn't really needed in some scenarios (like mine)? 

Additionally I noticed a possible miss on the TypeScript here. Observable.binding accepts three generics `<TSource, TReturn, TParent>`. Specifically, the `TParent` is passed through to the `BindingObserverImplementation` class and used for the context type on the binding call. But the Observable.binding() method doesn't quite pass the type all the way through - it just uses it in the return type. So, you could pass your types to the Observable.binding() call but they have no affect on the actual object they produce so TypeScript won't catch incorrect types in your parameter. Here's a super simple fix:

image

Probably another simple PR. Not really a huge problem, but kind of a nice improvement.

**Comment by EisenbergEffect** [comment]
I'd love to have more PRs :) Happy to have you contribute these improvements.

**Comment by tgoze** [comment]
Just a note, I'm awaiting CLA approval from my company...

**Comment by tgoze** [comment]
> @tgoze How are things going? Able to sign the CLA?

Still waiting on company approval unfortunately...

**Comment by awentzel** [comment]
> > @tgoze How are things going? Able to sign the CLA?
> 
> Still waiting on company approval unfortunately...

@tgoze, Is this still the case?  If no approval yet should we either have another person submit or abandon?

**Comment by tgoze** [comment]
> > > @tgoze How are things going? Able to sign the CLA?
> > 
> > 
> > Still waiting on company approval unfortunately...
> 
> @tgoze, Is this still the case? If no approval yet should we either have another person submit or abandon?

Unfortunately, no word. We should have another person submit!

**Comment by EisenbergEffect** [comment]
Assigning to myself. Thanks @tgoze !

**Review by awentzel — APPROVED** [review]

**Pull request closed without merging**
