### PR TITLE
fix: add user-select to button

### PR DESCRIPTION
**Pull request by rinaok**
# Pull Request

## 📖 Description

This is a fix for the button. The style of the button now includes `user-select: none; .
`
### 🎫 Issues

The text inside the button can be selected in mobile.
IMG_923E270291FB-1

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Thanks for the contribution @rinaok!
@chrisdholt can you take a look?

**Comment by chrisdholt** [comment]
> Thanks for the contribution @rinaok! @chrisdholt can you take a look?

I think this is going to be an interesting one. @rinaok, is the intent here to have this shipped to the old `@microsoft/fast-components` package? @EisenbergEffect, that package was removed prior to the `archives/fast-element-1` branch being snapped and has its own archive. To publish, I think we'll need to back-port those changes and completely decouple fast-components from the workspace in that branch, ensuring that it is locked to the now-latest version of `@microsoft/fast-foundation`.

If there's no urgent need to have this small fix backported, I think we could use this in the CLI which is what will generate the `fast-components` from now on.

As it stands now, this is certainly welcome, but the PR simply touches the foundation "base" styles which are used for testing.

**Comment by rinaok** [comment]
Hey @chrisdholt Yes, you are right. The intent was to have this shipped to the @microsoft/fast-components package.

**Comment by EisenbergEffect** [comment]
@chrisdholt I noticed this has been hanging out here without resolution for a while. How would you like to handle this?

**Comment by chrisdholt** [comment]
> @chrisdholt I noticed this has been hanging out here without resolution for a while. How would you like to handle this?

See the comment above - we can merge this for the sake of merging it, but the goal was to solve something else...

**Review by EisenbergEffect — APPROVED** [review]
Approving this since it's probably fine to merge to the foundation base styles. However, we'd need a new PR to fix this in fast-components, on the proper branch. We're trying to avoid that for now if possible and prefer to take updates to the CLI styles for vNext.

**Review by chrisdholt — APPROVED** [review]
I'll +1 what Rob mentioned and add that I think to fix this in the actual `fast-components` at this point likely doesn't make a ton of sense w/ the move to the CLI. My hope would be that a short-term fix for folks could be to simply include a quick bit of css locally. Since this is being applied on the `host`, it could be as simple as:

```css
fast-button {
    user-select: none;
}
```

**Comment by chrisdholt** [comment]
> > 
> 
> @chrisdholt Yes, that's exactly how I fixed it locally. Should I close this PR?

We'll get this in as part of our testing, I just wanted to make sure folks were aware that there wasn't any method of fixing this in the deprecated components package - thanks!

**Pull request merged**
