### PR TITLE
fix: [Combobox] Allow arbitrary text entry for 'inline' and 'both' autocomplete modes.

### PR DESCRIPTION
**Pull request by atmgrifter00**
# Pull Request

## 📖 Description

This is a more complete fix for Issue #6111 (previously attempted with PR #6145) . The one thing the previous PR didn't handle was allowing a user to enter arbitrary text for a value when the `autocomplete` mode was an `inline` variant.

### 🎫 Issues

- #6111
- #6145

## 📑 Test Plan

Modified an existing test to cover all of the current `autocomplete` mode states.

### General

- [x] I have included a change request file using `$ yarn change`
- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Comment by atmgrifter00** [comment]
I assume @radium-v should review this.

**Review by chrisdholt — APPROVED** [review]

**Review by radium-v — APPROVED** [review]

**Comment by chrisdholt** [comment]
@atmgrifter are you able to add this to the existing PR for cherry-pick? Thanks!

**Comment by atmgrifter00** [comment]
> @atmgrifter are you able to add this to the existing PR for cherry-pick? Thanks!

Should be!

**Comment by atmgrifter00** [comment]
> @atmgrifter are you able to add this to the existing PR for cherry-pick? Thanks!

@chrisdholt Done!

**Pull request merged**
