### PR TITLE
chore: update visual to web components

### PR DESCRIPTION
**Pull request by khamudom**
# Pull Request

## 📖 Description

This PR is a visual update to the components. Below is a brief overview of what has been done, to hopefully help give an idea of the changes that have been done. 
But please run the branch, if you can, as that will also give you a better look and feel of the components. Feedbacks are welcome.

The majority of the changes on the components are style updates to using the design tokens on different states, like rest, hover, active, and focus. Some of the components are also "grouped" in a way, where they are using similar tokens because from a base level, they look and interact the same. For example, checkbox, radio, and switch are smaller custom inputs so they use the same tokens on the border and background. Another is the menu and list flyouts (from select or combo box) have the same background tokens. Those are just a few examples.
Also updated some SVGs and fixture examples.

- To make sure the colors are in sync with the design, I changed the dark mode in `base-layer-luminance.ts` from `0.23` to `0.09`(#181818).
- Updated the base accent on `color-constants.ts`

- Here are some changes to some recipe files (src/color/recipes)
updated `focus-stroke.ts` changing the color contrast from `3.5` to `5.5`
updated `neutral-fill.ts` changing the direction to use `directionByIsDark(reference)`
updated `neutral-foreground.ts` adding hover, active and focus deltas
updated `neutral-foreground.spec.ts`
added `contrast-set-recipe.ts` - This recipe is used on `stroke-control-strong-recipe`

- Here are some changes to some design token files (src/design-tokens)
updated `baseHeightMultiplier` to set it from 10 to 8
updated `controlCornerRadius` to set it from 4 to 6
updated `layerCornerRadius` new corner radius, set to 6, used on `card` and `menu`
updated `neutral-fill` deltas to (rest: 4, hover: 4, active: 10, focus: 5)
updated `neutral-fill-input-active` delta to (-10)
updated `neutral-fill-stealth` deltas to (hover: 4, active: 10, focus: 4)
updated `neutral-fill-layer-rest` delta to (2)
updated `neutral-stroke` deltas (rest: 49, hover: 49, active: 90, focus: 49)
updated `neutral-foreground-recipe` to create deltas for hover, active, focus
added `neutral-stroke-input-fill` this token is used on inputs with filled appearance
added `stroke-control-strong` this token is used checkbox, radio, slider, outline button, and switch 

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Comment by SethDonohue** [comment]
Should the accordion have double dividers between sections?
Screen Shot 2021-10-29 at 2 34 49 PM

**Comment by SethDonohue** [comment]
Looks like there is a difference between the focused accent button and what is in the figma, a color difference perhaps on the box shadow?
Figma: 
Screen Shot 2021-10-29 at 2 43 29 PM
Your branch:
Screen Shot 2021-10-29 at 2 43 12 PM

**Comment by SethDonohue** [comment]
I don't see any updates on the date picker/calendar. Were you not supposed to update that one?
It's missing the focused, hover and pressed styles it seems.
Figma:
Screen Shot 2021-10-29 at 2 49 21 PM

Current:
Screen Shot 2021-10-29 at 2 46 18 PM
Screen Shot 2021-10-29 at 2 46 22 PM

**Comment by khamudom** [comment]
> I don't see any updates on the date picker/calendar. Were you not supposed to update that one? It's missing the focused, hover and pressed styles it seems. Figma: Screen Shot 2021-10-29 at 2 49 21 PM
> 
> Current: Screen Shot 2021-10-29 at 2 46 18 PM Screen Shot 2021-10-29 at 2 46 22 PM

Picker was added after. I will take a pass at it now.

**Comment by khamudom** [comment]
> A few questions on this, do these changes include:
> 
> * Updates to the sites:
>   
>   * Component Explorer
>   * Front page site that uses the components
> * Invalid states for form components such as text-field
> 
> Should this PR:
> 
> * Be merged into a feature branch
> * Be broken up into smaller PRs going into aforementioned feature branche so each component can be carefully scrutinized because, this is a lot of changes in a single PR
> * Include information on "next steps" for any of the changes that perhaps did NOT get made but will in the future

Good questions @janechu . As of this moment, there is no talk to updating the component explorer or front page site. My assumption is wherever the FAST components are used if they do not have any style overrides, will get the visual update. Someone, please correct me if I am wrong. 
Since this is just a visual update, it probably does not need to be in a feature branch. 
There are a lot of changes, but hopefully, my description update will help with the review.
@bheston may have thoughts on this since he went through with it in fluentui. As components get added are updated, I will keep the PR updated and make visual changes and add notes as we go.

**Comment by khamudom** [comment]
> Should the accordion have double dividers between sections? Screen Shot 2021-10-29 at 2 34 49 PM

Are you asking if this new design should have double borders, or are you saying I am missing double borders in the change? But if you are asking if there should be a double or single border, I think either one will work. @bheaston do you have any input?

**Comment by janechu** [comment]
> As of this moment, there is no talk to updating the component explorer or front page site. My assumption is wherever the FAST components are used if they do not have any style overrides, will get the visual update. Someone, please correct me if I am wrong. Since this is just a visual update, it probably does not need to be in a feature branch. There are a lot of changes, but hopefully, my description update will help with the review. @bheston may have thoughts on this since he went through with it in fluentui. As components get added are updated, I will keep the PR updated and make visual changes and add notes as we go.

The feature branch suggestion was so that you could merge component visual updates into a separate branch which would then be merged to master, thereby not having to have one gigantic branch that is hard to review.

Right now this is very difficult to review, it is almost inevitable that something *will* get missed in a PR of this size.

**Comment by janechu** [comment]
To add on to my previous comment, it would be much easier if you could do PRs that would include:

- Only a single components changes
- Screenshots of the before and after of that component in the PR body
- Note any additional state update styles that might have been included or any other non-trivial style changes

**Comment by khamudom** [comment]
> To add on to my previous comment, it would be much easier if you could do PRs that would include:
> 
> * Only a single components changes
> * Screenshots of the before and after of that component in the PR body
> * Note any additional state update styles that might have been included or any other non-trivial style changes

I agree that smaller changes are really beneficial for reviewing and also having before and after screenshots help with visual changes. @chrisdholt and @bheston since we kind of chatted about a feature branch, any comments on making a feature branch for this update? I am fine either way.

**Comment by chrisdholt** [comment]
> > To add on to my previous comment, it would be much easier if you could do PRs that would include:
> > 
> > * Only a single components changes
> > * Screenshots of the before and after of that component in the PR body
> > * Note any additional state update styles that might have been included or any other non-trivial style changes
> 
> I agree that smaller changes are really beneficial for reviewing and also having before and after screenshots help with visual changes. @chrisdholt and @bheston since we kind of chatted about a feature branch, any comments on making a feature branch for this update? I am fine either way.

I'm fine with moving to a feature branch. It'll take some time to move over there but it will likely make it much easier to not have regressions slip through the cracks. Thanks!

**Comment by khamudom** [comment]
> > > To add on to my previous comment, it would be much easier if you could do PRs that would include:
> > > 
> > > * Only a single components changes
> > > * Screenshots of the before and after of that component in the PR body
> > > * Note any additional state update styles that might have been included or any other non-trivial style changes
> > 
> > 
> > I agree that smaller changes are really beneficial for reviewing and also having before and after screenshots help with visual changes. @chrisdholt and @bheston since we kind of chatted about a feature branch, any comments on making a feature branch for this update? I am fine either way.
> 
> I'm fine with moving to a feature branch. It'll take some time to move over there but it will likely make it much easier to not have regressions slip through the cracks. Thanks!

OK. I will get the process started.

**Comment by SethDonohue** [comment]
> > Should the accordion have double dividers between sections? Screen Shot 2021-10-29 at 2 34 49 PM
> 
> Are you asking if this new design should have double borders, or are you saying I am missing double borders in the change? But if you are asking if there should be a double or single border, I think either one will work. @bheaston do you have any input?

I am assuming it should not have a double border like this by default. Is that correct?

**Comment by khamudom** [comment]
Will be moving these changes into a feature branch

**Pull request closed without merging**
