### PR TITLE
feat: enable FoundationElement.compose to accept template functions

### PR DESCRIPTION
**Pull request by EisenbergEffect**
# Description

This PR is part of the Design System vNext work and expands our capabilities for registering our web components to enable the developer to provide a function in place of template, styles, etc. The function will be executed when the element is being defined so that it has access to the configured element prefix, icon overrides, etc.

Here's an example of how this might be used to enable a component to be defined when it doesn't know the final tag name of its internal components and when it also wants to render default slotted icon content, but also enable the end-user to change the default icon for all instances of the component:

#### In @microsoft/fast-foundation

```ts
export class Foo extends FoundationElement {
  @attr baz;
}

export const FooTemplate = (context, definition) => html<Foo>`
  <${context.tagFor(Bar)} qux={x => x.baz}>
    <slot>
      ${definition.defaultIcon}
    </slot>
  </${context.tagFor(Bar)}>
`;
```

#### In @microsoft/fast-components or @fluentui/web-components

```ts
export const FooStyles = (context, definition) => css<Foo>`
  ...css here...
`;

export const foo = Foo.compose({
  baseName: 'foo',
  template: FooTemplate,
  styles: FooStyles
});
```

#### In MyApp

```ts
fluentUIDesignSystem()
  .register(
    foo({ defaultIcon: '...some html or even a template...' }),
    bar()
  )
  .applyTo(document.body);
```

>Note: I also renamed `FoundationElement.configure` to `FoundationElement.compose` and enabled it to use `this` internally so it can be called from the derived type (e.g. Foo above) and you don't need to pass the type again.

> Note: You do not need to pass a function for template or styles. You can also pass a template and styles object directly, just as in the past. Additionally, you can pass functions for element config, shadow dom options, etc. as well.

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [ ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [x] **New feature**: A change that adds functionality.

## Process & policy checklist

- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by chrisdholt — APPROVED** [review]

**Comment by nicholasrice** [comment]
I like this but I think we'll want to re-approach #4381 with it. I think *technically* this PR actually enables that issue's feature, but an author might need to do some cumbersome logic to additively merge or remove data.

I think we can figure that out though, this looks great!

**Review by nicholasrice — APPROVED** [review]

**Comment by EisenbergEffect** [comment]
@nicholasrice I just re-read your proposal. I totally didn't realize I was taking your `compose` naming scheme and interpreting it differently. If you think it makes more sense, we can change the method name back to `configure` (or to something else) and then add a `compose` method to do additive changes. Either way, I think we need what you propose in #4381 in addition to this PR so that folks can both replace the styles or simply add new styles on top of the base styles.

Do you want to just apply your work directly into this branch and then we can merge the final product? That might make it easier for you to work out the method names and the final shape of the API for all the scenarios. Whatever is easiest for you. Let me know.

**Comment by nicholasrice** [comment]
@EisenbergEffect I think we can get this in and follow up with an implementation for #4381

**Comment by EisenbergEffect** [comment]
@Ibrahimmaga It looks like Playwright is consistently failing. Can you advise?

**Review by janechu — APPROVED** [review]

**Comment by Ibrahimmaga** [comment]
I have a PR that will fix the Issue. Playwright version 1.9 just got broken that what we are using on the CI. I downgraded to 1.8 and it’s working great 👍.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
