### PR TITLE
fix: move setAttribute calls for proxy elements to connectedCallback

### LINKED ISSUE #3456: Runtime error in <fast-button> and <fast-anchor>
**Describe the bug; what happened?**

There is a runtime error:
```console
Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes
```

**What are the steps to reproduce the issue?**

Example:

1. Add <fast-button> to the page using `createElement` or `createElementNS`

**Is there any additional context?**

This appears to be because there is a modification to an attribute in the constructor as indicated by the top answer in this post: https://stackoverflow.com/questions/43836886/failed-to-construct-customelement-error-when-javascript-file-is-placed-in-head

We should not therefore be setting any DOM in the constructor and should wait for the `connectedCallback`.

### PR DESCRIPTION
**Pull request by chrisdholt**
# Description
This PR fixes an issue where attributes were defined too early for the custom element, specifically as it relates to form associated elements. This work moves the work to set proxy attributes to the connected callback.

Closes #3456 

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/en/contributing/standards) for this project.

### CODE REVIEW

**Comment by janechu** [comment]
I have created a branch with `createElement` and applied your changes - `users/janechu/custom-element-test`, still getting an error.

**Comment by janechu** [comment]
By setting `appearance` as undefined in the button this appears to fix the problem, I think this indicates these `attr` default settings are happening during the ctor phase, causing an issue. See https://github.com/microsoft/fast/commit/726db0cfb7730b4f4ec34d7616168be6adabfd03

**Comment by chrisdholt** [comment]
> By setting `appearance` as undefined in the button this appears to fix the problem, I think this indicates these `attr` default settings are happening during the ctor phase, causing an issue. See [726db0c](https://github.com/microsoft/fast/commit/726db0cfb7730b4f4ec34d7616168be6adabfd03)

Yes, as I was building your branch I realized that I had started working on that, but it was on your branch. I jumped back to apply some changes and spaced. I think we'll need to set the default appearance differently.

**Comment by chrisdholt** [comment]
@janechu pushed an update. I don't get an error thrown here when testing on your branch. @EisenbergEffect can you take one more look at this when available? One slight change made since you signed off.

**Pull request merged**
