### PR TITLE
Update blazer.md documentation (typo)

### PR DESCRIPTION
**Pull request by AaronCTech**
Adding PR for simple typo

# Pull Request

### General

- [ ] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Review by awentzel — APPROVED** [review]

**Review by nicholasrice — APPROVED** [review]

**Comment by nicholasrice** [comment]
@AaronCTech if you're able to run `yarn change` from the package root and follow the prompts we'll be able to get this in. Thanks!

**Review by chrisdholt — APPROVED** [review]

**Review by EisenbergEffect — APPROVED** [review]

**Comment by EisenbergEffect** [comment]
Assigning to myself to follow up on merge after the change file addition. @AaronCTech Let me know if you have any questions or trouble the process.

**Comment by AaronCTech** [comment]
I certainly can!

Sorry, I’d been mentally filtering these emails :)

**Review by raghavthind2005 — APPROVED** [review]

**Comment by awentzel** [comment]
I created the change file for you @AaronCTech, unfortunately, the system seems to require you need to sign the CLA again. Once this is done, I think we're safe to merge.  I'm sorry it's take so long to get this through.

**Comment by AaronCTech** [comment]
Not your fault, it’s totally mine. We closed on our house today, so as soon
as I get my setup back up and running, we’re gravy!

**Pull request merged**
