### PR TITLE
Set min-width: 0 on tree-item.content-region

### LINKED ISSUE #5732: fix: tree item shrinking blocked in @microsoft/fast-components
# 🐛 Bug Report

If a tree view is tuned to have a constraint minimal width and its text items are styled to display overflow with ellipsis, it does not work. The flex shrink is blocked by the text size (see screenshot below). This is well described by that [article](https://css-tricks.com/flexbox-truncated-text/) - and the solution proposed their does work but requires a style change in the Shadow node.

## 💻 Repro or Code Sample

Reproduced on using [the components explorer](https://explore.fast.design/components/fast-tree-view):

```html
<div style="width:100px;">
    <fast-tree-view style="min-width:auto;">
        <fast-tree-item style="overflow-x:hidden; text-overflow: ellipsis; white-space: nowrap;">Tree item 1<fast-tree-item style="overflow-x:hidden; text-overflow: ellipsis; white-space: nowrap;" slot="item">Tree item 1 - 1</fast-tree-item>
        </fast-tree-item>
        <fast-tree-item style="overflow-x:hidden; text-overflow: ellipsis; white-space: nowrap;">Tree item 2</fast-tree-item>
    </fast-tree-view>
</div>
```

## 🤔 Expected Behavior

Text overflow should be replaced by ellipsis

## 😯 Current Behavior

Text overflow is hidden.

image

## 💁 Possible Solution

Set `min-width: 0;` to `.content-region` TreeItem style.

## 🔦 Context

We are including the tree view in a sidebar:

image

> In the above screenshot, the `min-width: 0;` fix is included. Hence it is working.

## 🌍 Your Environment

* OS & Device: Debian 11 PC
* Browser Mozilla FireFox 98.0
* Version 2.21.9

### PR DESCRIPTION
**Pull request by fcollonval**
# Pull Request

## 📖 Description

Add story to demonstrate setting min-width: 0 on tree item content-region to allow text overflow with ellipsis.

See https://css-tricks.com/flexbox-truncated-text/

### 🎫 Issues

Fix #5732

## 📑 Test Plan

Add story to check the change

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Comment by scomea** [comment]
I believe this is achievable without this change using 'part' syntax.  I'm simultaneously wondering if this is change is too specific to a particular implementation or whether we should make truncating with ellipse the default behavior.

**Comment by fcollonval** [comment]
Thanks for the tip about `part` @scomea. I agree with you that it may be seen as too specific (although I don't have a counter argument). I updated this PR to just add a story using _part_ styling. What do you think?

**Review by EisenbergEffect — APPROVED** [review]

**Comment by scomea** [comment]
@bheston Any thoughts on whether the default tree item should auto-ellipse?

**Comment by bheston** [comment]
> @bheston Any thoughts on whether the default tree item should auto-ellipse?

That's a good question. I think most experiences truncate or ellipsis tree items, but it's not necessarily universal behavior between components. For instance, some lists wrap instead. This would be cool as a design token. I'd like to think more about how to incorporate that, but for now this is a good example.

**Review by raghavthind2005 — APPROVED** [review]

**Review by chrisdholt — APPROVED** [review]
Thanks @fcollonval!

**Pull request merged**
