### PR TITLE
chore: remove adaptive ui related packages

### PR DESCRIPTION
**Pull request by chrisdholt**
# Pull Request

## 📖 Description
This PR removes adaptive UI related packages as they are now fully supported and represented at the Adaptive Web community.

As part of this, errors were being thrown in the website preventing building as the site relies on fast-components and the alpha versions were conflicting with the dependencies of fast-components. This PR also includes a subtle change to not include the website as a package and instead sets it up to rely solely on the published stable versions.

### 🎫 Issues
N/A

## 👩‍💻 Reviewer Notes
As the website is no longer included as a package, it needs to have packages installed within the directory and be independently built (it's no longer built as part of the prepare process for all packages).

## ⏭ Next Steps
N/Aa

### CODE REVIEW

**Comment by nicholasrice** [comment]
@chrisdholt I think we should delete fast-figma-plugin-msft too, since it's very stale and intended to implement a lot of the design-token opinion that was present in fast-components. Thoughts?

**Comment by KingOfTac** [comment]
I think that makes sense as well since the plugin is also being developed in the adaptive web community.

**Comment by chrisdholt** [comment]
> 

Updated with removal of the plugin as well!

**Review by bheston — APPROVED** [review]
I was going to submit this at some point soon, but had been holding on updating the color explorer, which suffered the same issue you mentioned about the website.

I think it's fine removing all this now, but I think we should also either unpublish `colors.fast.design` or replace it with a simple redirect back to `fast.design` or the Fluent UI Storybook page that replaced it.

We should also officially mark the published `@microsoft/adaptive-ui` package as deprecated. Ideally link to the new one `@adaptive-web/adaptive-ui` if possible.

**Review by nicholasrice — APPROVED** [review]

**Pull request merged**
