### PR TITLE
fix: only store removed views if it cant be reused right away

### PR DESCRIPTION
**Pull request by prudepixie**
# Pull Request

## 📖 Description

Currently in repeat directive's updateViews() function, we loop through the splices once to track all the removed views, then we loop through the splices array again to attempt to reuse the removed views if there are equal or more added items.
This PR reuse the removed views right away and only store them if there are leftover removed views to be used in the next loop.

### 🎫 Issues
https://github.com/microsoft/fast/issues/6161

### General

- [x] I have included a change request file using `$ yarn change`
- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Comment by scomea** [comment]
Seems like an improvement.  I've wondered if there might be cases where more persistent cacheing might help perf, thinking of data displays that update frequently. Something like adding a `viewCacheSize` prop to repeat directives.

**Comment by prudepixie** [comment]
> Seems like an improvement. I've wondered if there might be cases where more persistent cacheing might help perf, thinking of data displays that update frequently. Something like adding a `viewCacheSize` prop to repeat directives.

That's interesting, if we can predict the size of the views it could help memory allocation.  But not entirely sure how we'd be able to approach that, maybe around the concept of pagination, would have to think about it.

**Comment by prudepixie** [comment]
Shows general improvement in both memory and execution time on splice operations:
updateView 3
updateView 2
updateView 1

**Review by EisenbergEffect — DISMISSED** [review]
A couple minor nits, but otherwise very, very cool! Main issue is that we need to fix up the change file before merging.

**Review by nicholasrice — APPROVED** [review]
looks good to me!

**Review by chrisdholt — APPROVED** [review]

**Pull request merged**
