### PR TITLE
chore: correct issues label url

### PR DESCRIPTION
**Pull request by JazibJafri**
# Description

This change updates the url pointing to `good-first-issue` label on github to the correct label `community:good-first-issue`

## Motivation & context

`Joining the community` section on fast website points to correct github label for `community:good-first-issue`

## Issue type checklist

- [x] **Chore**: A change that does not impact distributed packages.
- [ ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/en/contributing/standards) for this project.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Good and important catch @JazibJafri . Thank you!

**Comment by JazibJafri** [comment]
@EisenbergEffect do I have to worry about two of the checks failing? If I do, it'd be great if anyone can let me know what I can do to fix them.

**Comment by EisenbergEffect** [comment]
@JazibJafri No need for you to worry about that. We've got some issues in our pipeline we need to address.

**Comment by JazibJafri** [comment]
@EisenbergEffect very well, thanks.

**Pull request merged**
