### PR TITLE
chore: update to prettier@2.7.1 

### PR DESCRIPTION
**Pull request by nicholasrice**
# Pull Request

## 📖 Description
Updates to prettier@2.7.1 across the project. This will allow us to use the latest TypeScript language features, including the [override](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#override-and-the---noimplicitoverride-flag) keyword and [labeled tuple elements](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#labeled-tuple-elements).

## 👩‍💻 Reviewer Notes
I've only directly edited the projects package.json files. All changes to .ts files are a result of running prettier against the project.

This should wait for #6286 to go in so @bheston doesn't have to resolve conflicts for automated changes.

### General

- [ ] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Review by chrisdholt — APPROVED** [review]

**Review by EisenbergEffect — COMMENTED** [review]
I think this is going to cause a huge set of merge conflicts between Brian's foundation PR and my context PR. Maybe we should wait on this until those are merged?

**Comment by EisenbergEffect** [comment]
> I think this is going to cause a huge set of merge conflicts between Brian's foundation PR and my context PR. Maybe we should wait on this until those are merged?

And...just saw your note on exactly this. Doh.

**Review by EisenbergEffect — APPROVED** [review]
Pending merge of Brian's foundation PR and my context PR.

**Review by awentzel — APPROVED** [review]

**Comment by bheston** [comment]
I just noticed this was still out pending the foundation PR. While I've broken a few pieces off of that, it's still going to be a large change set, but I think it's almost ready pending one more PR merged and then rebased.

How about we unblock this (from my PR perspective) and I can just manually update the foundation package.json and run prettier locally before I rebase once this has gone in. I'm not sure if the PR Rob was working on is merged yet or not.

**Pull request closed without merging**
