### PR TITLE
Add publisher to syntax highlighting extension

### PR DESCRIPTION
**Pull request by radium-v**
# Pull Request

## 📖 Description

* Adds the `ms-fast` publisher to the extension manifest for the `fast-tagged-templates` extension.
* Adds the `ms-fast.fast-tagged-templates` extension to the VS Code recommended extensions configuration for this repository.
* Updates the README with a link to the extension on the Visual Studio Code Marketplace website.

## 👩‍💻 Reviewer Notes

The tagged template extension is published here: https://marketplace.visualstudio.com/items?itemName=ms-fast.fast-tagged-templates

The process for publishing and updating the marketplace is currently manual, though we're looking into how we might be able to make the updating process more hands-off/automated.

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [x] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by chrisdholt — APPROVED** [review]
Thanks @radium-v!

**Review by EisenbergEffect — APPROVED** [review]

**Comment by EisenbergEffect** [comment]
@radium-v Sweet! As a follow-up PR, would you be able to update our docs with this plugin? There a VS Code pages on our site that lists some other plugins. It would be cool to have ours listed there instead. You would need to update both the previous and current docs. So, same change in two places. Let me know if you need me to point you at that or answer any questions. Thanks for putting this together.

**Comment by EisenbergEffect** [comment]
@radium-v I was just testing this out and notices that in VS Code I didn't see HTML element documentation of get tag completion. Any ideas how to get that working? I think that worked with the previous plugin I as using.

**Comment by radium-v** [comment]
@EisenbergEffect This is probably due to the extension not having a [language server](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) - its main purpose when I built it was merely to provide [syntax highlighting](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide). But it could definitely do both! Please create an issue so we can track it.

**Comment by EisenbergEffect** [comment]
> @EisenbergEffect This is probably due to the extension not having a [language server](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) - its main purpose when I built it was merely to provide [syntax highlighting](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide). But it could definitely do both! Please create an issue so we can track it.
> 
> Edit: here's some more related documentation: https://code.visualstudio.com/api/language-extensions/embedded-languages

Here you go: https://github.com/microsoft/fast/issues/6336

**Pull request merged**
