### PR TITLE
fix: dialog delays for a frame before finding tabbable children

### PR DESCRIPTION
**Pull request by scomea**
# Description
The dialog component uses [tabbable](https://github.com/focus-trap/tabbable) to build a local tab queue.  Currently tabbable is called on the dialog's connected() callback which is before child elements have had a chance to fully load.  As a result web components that should be in the tab queue have not yet updated their tabIndex values to "0" so they don't get added to the queue.  This change delays the call to tabbable until after a DOM update.

This does not resolve the issue that the button component isn't discovered by tabbable because the "button" tag is hidden in the shadow dom and the component itself does not have a non-negative tab index which is refererred to in https://github.com/microsoft/fast/issues/4035

## Motivation & context
Tabbable web components should show up in our dialog's tab queue.

## Issue type checklist
- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**
- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by EisenbergEffect — APPROVED** [review]

**Comment by EisenbergEffect** [comment]
I think this approach works for the current scenarios but I wonder if it will run into other issues later. For example, what if the dialog has conditional rendering of its children and at some point during dialog interaction, new DOM gets conditionally rendered which has focusable controls. Will tabbable prevent those from being focused? I don't really know much about tabbable (other than I'd like to get rid of the 3rd party dependency if we can). If this scenario is a problem we may need to switch to using the `children` decorator on the template with a setting of `subtree: true` so that we can be notified when any child is added/removed and re-run tabbable.

**Comment by scomea** [comment]
@EisenbergEffect Yeah, there are some holes.  Even the approach you suggest would not catch a case where a child had its tab index change from negative to positive after load or child change (our components do that).  We may need to run it on each keystroke.

**Comment by EisenbergEffect** [comment]
The underlying mutation observer could be configured to callback on attribute changes as well. I've never actually used it in that mode and don't know the perf implications... Maybe it's not too bad since you don't have a ton of dialogs at once and they usually aren't too complicated. Perhaps we configure that and if the change is a dom structure change or a tab index change, then we re-run tabblable, otherwise ignore?

**Comment by scomea** [comment]
I opened a tracking bug - https://github.com/microsoft/fast/issues/4038

**Review by nicholasrice — APPROVED** [review]

**Pull request merged**
