### PR TITLE
chore: demo more suitable placeholder

### PR DESCRIPTION
**Pull request by bashmish**
# Pull Request

## 📖 Description

The demoed placeholder was probably copy-pasted from the text-field demo and is confusing in the context of the number field.

image

### 🎫 Issues

No reported issues.

## 👩‍💻 Reviewer Notes

N/A

## 📑 Test Plan

N/A

### General

- [x] I have included a change request file using `$ yarn change`
- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [x] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## ⏭ Next Steps

N/A

### CODE REVIEW

**Comment by bashmish** [comment]
I need to look into how to create a change file, because this PR was created from GitHub website. It's a bit hard for such small fix, but OK :)

**Review by scomea — APPROVED** [review]

**Review by EisenbergEffect — APPROVED** [review]

**Comment by EisenbergEffect** [comment]
@bashmish We've got one issue which is that our build requires a change file, even for docs/examples changes like this. So, you would need to check out the branch and run `yarn change` from the root of the repo to generate that. Then push your commit.

**Comment by bashmish** [comment]
I made a "chore" commit and a change of "none" type looking at https://github.com/microsoft/fast/pull/4763/files
Hope it works! :)

**Comment by EisenbergEffect** [comment]
Merged. Thanks for the fix!

**Pull request merged**
