### PR TITLE
Update Docusaurus to v3, initial pruning of docs and setup for FASTElement 2.0.0

### PR DESCRIPTION
**Pull request by janechu**
# Pull Request

## 📖 Description

This pull request does the following:
- Updates docusaurus to v3
    - This necessatated some editing of the docs as they were not compliant with the `mdx` format, a document checker has been added to the package.json scripts
- Remove docs in v2.0.0 that had links to documents that will not be included in the v2.0.0 documentation site
- Rename "legacy" to 1.0.0 for clarity (this still includes documentation for removed packages but documentation site going forward will only refer to the `@microsoft/fast-element` package version and document that package).
- Removal and simplification of some legacy React components made for Docusaurus.
- Some decoupling from dependencies in the mono-repository, these are all `devDependencies`, simple configuration updates, or small TypeScript changes.

## 👩‍💻 Reviewer Notes

This is only the initial step to get the documentation site to be versioned, have a limited `@microsoft/fast-element` documentation, and be on the latest docusaurus version. Still needed is updating the documentation itself, this will occur in future PRs prior to versioning `@microsoft/fast-element` to 2.0.0.

Edit: One of the issues with this update is that any updates to the package dependencies is very difficult (to put it mildly), yarn 1 does not react appropriately to nohoisting and fixing versions with "resolution" in the root level package.json has over time caused a bit of a rats nest. This has caused me to have to change some of the tsconfig files and skip the foundation toolbar tests as well as explicitly fix and add certain package dependencies to force packages to build and test correctly. Please look at the changes with a critical eye, but know that many of these changes were done only to get this change in, and that there are plans to upgrade to npm and remove yarn as a dependency after some cleanup to the project which will make that process much easier.

### General

- [ ] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [x] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by KingOfTac — COMMENTED** [review]
Only thing I noticed was the mermaid charts not rendering on the introduction pages for both v1 and v2

**Comment by janechu** [comment]
> Only thing I noticed was the mermaid charts not rendering on the introduction pages for both v1 and v2

Good catch, I'll make another PR before I update content to get the mermaid charts working, looks like that was changed between docusaurus versions.

**Comment by scomea** [comment]
Under "community contributions v2" -
image

**Comment by scomea** [comment]
Builds fine for me.  Did a very cursory initial pass on content.

**Review by eljefe223 — APPROVED** [review]

**Review by chrisdholt — APPROVED** [review]

**Pull request merged**
