### PR TITLE
fix: update react-dev-utils to 11.0.4 & is-svg@^4.2.2:

### PR DESCRIPTION
**Pull request by Ibrahimmaga**
Dependabot cannot update react-dev-utils to a non-vulnerable version
# Description
Upgrade react-dev-utils to version 11.0.4 and is-svg@^4.2.2:or later. For example:

react-dev-utils@^11.0.4:
  version "11.0.4"

is-svg@^4.2.2
this module performs a quick-and-dirty check. It's fast, but in certain cases it will give incorrect results.
Returns true for an SVG-like string that isn't well-formed or valid: <svg><div></svg>
If you want to make certain that your SVG is valid, try parsing it with libxmljs.

Vulnerable versions: >= 0.4.0, < 11.0.4
Patched version: 11.0.4
## Motivation & context
resolve dependabot alerts

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [x] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by janechu — APPROVED** [review]

**Comment by janechu** [comment]
Bug fixes should be preceded by "fix" not "bug" and should be lowercase. I've corrected the PR title to reflect.

**Review by nicholasrice — APPROVED** [review]

**Comment by awentzel** [comment]
Shouldn't there be package bumps also in package.json file or files?

**Comment by Ibrahimmaga** [comment]
> Shouldn't there be package bumps also in package.json file or files?

we are not using beachball on this PR.

**Comment by awentzel** [comment]
> > Shouldn't there be package bumps also in package.json file or files?
> 
> we are not using beachball on this PR.

What I mean is, generally when upgrading dependencies, which are packages in themselves, that would be done on package.json file and then by running yarn install those dependencies would update the yarn.lock file which would then get committed.  I don't see any dependencies being updated with this PR.  So, how did yarn.lock then get created?

**Comment by Ibrahimmaga** [comment]
> > > Shouldn't there be package bumps also in package.json file or files?
> > 
> > 
> > we are not using beachball on this PR.
> 
> What I mean is, generally when upgrading dependencies, which are packages in themselves, that would be done on package.json file and then by running yarn install those dependencies would update the yarn.lock file which would then get committed. I don't see any dependencies being updated with this PR. So, how did yarn.lock then get created?

I can't see. I'm sure I have updated package.json let me double check

**Comment by Ibrahimmaga** [comment]
> > > > Shouldn't there be package bumps also in package.json file or files?
> > > 
> > > 
> > > we are not using beachball on this PR.
> > 
> > 
> > What I mean is, generally when upgrading dependencies, which are packages in themselves, that would be done on package.json file and then by running yarn install those dependencies would update the yarn.lock file which would then get committed. I don't see any dependencies being updated with this PR. So, how did yarn.lock then get created?
> 
> I can't see. I'm sure I have updated package.json let me double check

both of them are not in package.json. perhaps we don't need it there. I usually do the global search but they are not in package.son. They are no in master neither.

**Pull request merged**
