### PR TITLE
Fix: NVDA announces button slots as clickable

### PR DESCRIPTION
**Pull request by KingOfTac**
# Pull Request

## 📖 Description
This PR fixes an issue where NVDA announces slots as clickable if they have an onClick event bound.

Just as a general FYI for those interested. The reason why NVDA announces "clickable clickable button" when a svg is in the start slot is because if you set `aria-hidden` on the svg it is hidden from the SR however NVDA announces elements with a click handler bound to them as clickable so for `FASTButton` where it was binding click handlers to all the slots the announcement would look like "clickable '' clickable [default slot content] button". If the svg is in the end slot then it announces "clickable [default slot content] clickable '' button". This same pattern would hold true for any content in the named slots.

### 🎫 Issues
NVDA would announce the named slots in `Button` as clickable if they contained any nodes because the slots had the onClick event bound to them. More info on the NVDA behavior here: https://github.com/nvaccess/nvda/issues/5830

## 👩‍💻 Reviewer Notes
I removed the `disconnectedCallback` from `Button` since all it was doing was removing the event listeners from the slots. I also removed the handleClick method since the internal button already handles disabling clicks when the disabled attribute is present. All tests continue to pass after this change.

## 📑 Test Plan
I added a new story in storybook with an icon slotted into the start slot to show that the "clickable, clickable" announcement no longer happens. To see the old behavior go to this repro and tab through the buttons. https://stackblitz.com/edit/typescript-qp1vkw?file=index.html

### General

- [X] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [X] I have tested my changes.
- [X] I have updated the project documentation to reflect my changes.
- [X] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [X] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## ⏭ Next Steps
We should see if this can be backported to vCurrent and the fast/fluent component packages

### CODE REVIEW

**Comment by KingOfTac** [comment]
Second time's the charm. I also added some more info to the description and revised the next steps section. Since I already went ahead and checked all the components in foundation for this behavior.

**Comment by KingOfTac** [comment]
I was going to remove `defaultSlottedContent` as well since it is no longer used after removing the click handler, but it's a part of `FASTButton`'s public api so I wanted to get everyone's thoughts first in case it is still useful for hooking into externally.

**Review by chrisdholt — APPROVED** [review]

**Comment by nicholasrice** [comment]
@KingOfTac your PR description says you moved the onClick to the template, but I don't see that. Is the PR description just not reflective of the actual change?

**Comment by chrisdholt** [comment]
> @KingOfTac your PR description says you moved the onClick to the template, but I don't see that. Is the PR description just not reflective of the actual change?

I think this is due to copy/paste. In the prior PR (which got borked) I suggested we remove the behavior altogether. If the element is disabled the actual button should be disabled, thus anything slotted should be (technically) disabled...

**Comment by KingOfTac** [comment]
> @KingOfTac your PR description says you moved the onClick to the template, but I don't see that. Is the PR description just not reflective of the actual change?

Oh oops. I missed updating that part. The click handler was removed entirely since it was no longer needed.

**Comment by KingOfTac** [comment]
@nicholasrice I updated that section to reflect the actual changes. Thanks for the heads up.

**Review by nicholasrice — APPROVED** [review]
thanks @KingOfTac!

**Pull request merged**
