### PR TITLE
docs: updates to intro page and documentation

### PR DESCRIPTION
**Pull request by huynhicode**
# Pull Request

## 📖 Description

This PR includes:

- updates to the [Introduction](https://www.fast.design/docs/introduction) page including the addition of diagrams (see screenshots 1 and 2 below)
- removal of references to FluentUI from the following pages:
     - Using the Components > [Components QuickStart](https://www.fast.design/docs/components/getting-started)
     - Resources > [FAQ](https://www.fast.design/docs/resources/faq)
     - Creating Design Systems > [Overview](https://www.fast.design/docs/design-systems/overview)
     - Using the Components > Components > [badge](https://www.fast.design/docs/components/badge)
- addition of two packages:
     - [Mermaid](https://mermaid-js.github.io/mermaid/#/): "A Javascript based diagramming and charting tool that renders Markdown-inspired text definitions to create and modify diagrams dynamically."
     - [mdx-mermaid](https://github.com/sjwall/mdx-mermaid): "A Docusaurus v2 compatible MDX plugin for displaying diagrams."  Listed as a Docusaurus resource [here](https://docusaurus.io/community/resources#features).
- addition of generated-index, which generates "an index page that displays all the direct children of this category" (see screenshots 3 and 4 below)

FYI: The only reference to FluentUI remaining will be the [Blazor](https://www.fast.design/docs/integrations/blazor) integration guide.

Related issues:
- https://github.com/microsoft/fast/issues/4309
- https://github.com/microsoft/fast/issues/4315

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## ⏭ Next Steps

Screenshots:

1) Intro page - light mode:

intro_light

2) Intro page - dark mode:

intro_dark

3) Generated index - light mode:

generated-index_light

4) Generated index - dark mode:

generated-index_dark

### CODE REVIEW

**Review by EisenbergEffect — APPROVED** [review]
We might need to have someone do a more thorough review of the yarn.lock changes. Otherwise, looks good. It will be nice to have a few more visuals and the index pages.

**Comment by huynhicode** [comment]
> @huynhicode Do you know if it's possible to center the mermaid visuals?

That's a great suggestion @EisenbergEffect; let me try to center the diagrams.

**Comment by huynhicode** [comment]
> We might need to have someone do a more thorough review of the yarn.lock changes. Otherwise, looks good. It will be nice to have a few more visuals and the index pages.

That sounds good @EisenbergEffect, thank you.  All the sidebar topics will have an index page including the subtopics that have expanded sections.  Sorry for not clarifying in my PR.  I will go through the intro page and create additional diagrams.

**Comment by EisenbergEffect** [comment]
@huynhicode I didn't mean that you need to go add more visuals to the intro. I meant "when this is published, it will be nice to have these new visuals".

**Comment by huynhicode** [comment]
> @huynhicode I didn't mean that you need to go add more visuals to the intro. I meant "when this is published, it will be nice to have these new visuals".

OH 🤦🏻‍♀️ 😅. I agree

**Comment by huynhicode** [comment]
@EisenbergEffect I centered the diagrams:

Light mode:

intro_updated_light

Dark mode:

intro_updated_dark

**Comment by EisenbergEffect** [comment]
@huynhicode Awesome! I had one other thought just now. Is it possible to remove the gray boarder around the diagram?

**Comment by huynhicode** [comment]
> @huynhicode Awesome! I had one other thought just now. Is it possible to remove the gray boarder around the diagram?

Like this?

intro_no-outline_light

intro_no-outline_dark

**Pull request merged**
