### PR TITLE
chore(docs): display last update time

### PR DESCRIPTION
**Pull request by micalevisk**
# Pull Request

## 📖 Description

Prior this PR, there was no way to tell if we are reading a new version of the docs besides reading it entirely.

Now we'll get something like this:

image

### General

- [ ] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by EisenbergEffect — APPROVED** [review]
Awesome! Thank you 😄

**Comment by EisenbergEffect** [comment]
@micalevisk Are you able to sign the CLA?

**Comment by micalevisk** [comment]
@EisenbergEffect do I need? 

image

I like the idea of having a CLA but I don't know how to do that, tbh.  :smile: https://cla.microsoft.com/

**Comment by EisenbergEffect** [comment]
Looks like we're all good now. Thanks @micalevisk !

**Comment by EisenbergEffect** [comment]
Thanks for this nice improvement!

**Pull request merged**
