### PR TITLE
Users/imaga/code coverage using node v8 instead of babel

### PR DESCRIPTION
**Pull request by Ibrahimmaga**
Codecov https://about.codecov.io/
Semantic-Relese: https://github.com/semantic-release/semantic-release

# Description
Codecov has a benefit which you don't have to provide a path like code climate, It will automatically test every code in the repos:
The Semantic-Release: automates the whole package release workflow including: determining the next version number, generating the release notes and publishing the package. 
For this work, Beachball Publish is being consider in the team. The real implementation is a work ahead.

1. https://about.codecov.io/:
    -  create a codecov token to authenticate and run codecov in CI workflow
2. Semantic release
    -  Only allow squash merging of pull requests
    -  Install https://github.com/apps/semantic-pull-requests
    -  Create npm token using `npm token create` or https://www.npmjs.com/settings
    -  Add token to repo secrets as `SEMANTIC_RELEASE_TOKEN`
    -  Add release workflow file to `ci-nightly.yml`
    -  Set `version` to `0.0.0-development` in package.json
    - `npm i -D semantic-release`
    -  Use semantic commit messages
    -  Create a pull request
    
## Motivation & context

code coverage, performance, versioning and documentation

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [ ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [x] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [x] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by chrisdholt — COMMENTED** [review]
@Ibrahimmaga Can we create an issue tracking the removal of the semantic release check when we move to beachball? At that point in time it will not matter what our PR titles are as the check will take place in a JSON file in PR which can also be checked during CI.

**Comment by awentzel** [comment]
@Ibrahimmaga could you expand on the performance improvements to using V8 instead of Babel as this was the original purpose of the investigation.

**Review by awentzel — CHANGES_REQUESTED** [review]
blocking for the moment to better understand the implications of changing this.  

A friendly reminder to update the title of the PR to conform to our policies.

I like the idea of moving code coverage to a nighty build process as well to reduce pipeline times keeping our development and contribution teams efficient.

**Comment by Ibrahimmaga** [comment]
This PR will be close. It has a lot of miss communication and clear objective for the PR.

**Pull request closed without merging**
