### PR TITLE
Update webpack integration documentation

### PR DESCRIPTION
**Pull request by meyunus**
# Pull Request

## 📖 Description
Update [webpack integration documentation](https://www.fast.design/docs/integrations/webpack) to be compatible with `webpack-dev-server@4.0.0` according to [webpack migration guidelines](https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md).

The `writeToDisk` option was moved to` devMiddleware` option, and the `lazy `option was removed.

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by EisenbergEffect — APPROVED** [review]
Awesome! Thank you!

**Comment by EisenbergEffect** [comment]
@meyunus Looks like we need a change record for this for our system. Can you run `yarn change` at the root of the repo, follow the prompts and then push that to GitHub? After that we should be able to get this merged.

Thanks!

**Comment by meyunus** [comment]
@EisenbergEffect done!

**Review by robarbms — APPROVED** [review]

**Comment by EisenbergEffect** [comment]
Thanks @meyunus !

**Pull request merged**
