### PR TITLE
chore: fix broken cdn address

### PR DESCRIPTION
**Pull request by BrunoBlanes**
# Description
Removed an extra '@' from the CDN link.

## Motivation & context
Fixes the CDN address.

## Issue type checklist

- [x] **Chore**: A change that does not impact distributed packages.
- [ ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Comment by BrunoBlanes** [comment]
I realize now that the reason for the second `@` is to escape the first character on Razor pages, however the page instructs the user to place the script on `index.html` and not on `_Layout.cshtml`. Therefore, a decision need to be made on where the script should be put and then update the link accordingly.

**Comment by BrunoBlanes** [comment]
I think if we want to cover both scenarios, it should not contain the second character, because that gives a false idea of the original address. Escaping should be up to the developer.

**Comment by EisenbergEffect** [comment]
Good points. This makes sense. Perhaps we make this change and then also add a `:::note` section that indicates that the extra `@` is needed when in a Razor view. Thoughts?

**Review by EisenbergEffect — APPROVED** [review]

**Review by chrisdholt — APPROVED** [review]
Agree on the note aspect - I think we've seen this change back and forth a few times. Adding a note here would be helpful :)

**Comment by EisenbergEffect** [comment]
@BrunoBlanes Would you be willing to add another commit to this PR with the note? Here's what the syntax is:

```
:::note
Your content here
:::
```

**Comment by BrunoBlanes** [comment]
How about this?
```
:::note
If you are setting up FAST on a Blazor Server project, you will need to escape the '@' character by repeating it in the source link. For more information check out the [Razor Pages syntax documentation](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor#razor-syntax).
:::
```

**Review by nicholasrice — APPROVED** [review]

**Comment by EisenbergEffect** [comment]
@BrunoBlanes That's perfect. Go ahead and add that if you don't mind. Ping me and I'll get this merged.
Thanks for contributing!

**Review by EisenbergEffect — APPROVED** [review]

**Pull request merged**
