### PR TITLE
WIP: fix: move component proxy creation to connectedCallback

### LINKED ISSUE #3741: bug: input proxy causes empy label to display
**Describe the bug; what happened?**

When a proxy input is needed it is created in the slot. This prevents the `label__hidden` class from being added.

Edge:
```
<fast-text-field>
  #shadow-root
    <label class="label label__hidden" part="label" for="control">
      <slot></slot>
    </label>
    ...
</fast-text-field>
```

Firefox:
```
<fast-text-field>
  #shadow-root
    <label class="label" part="label" for="control">
      <slot><input /></slot>
    </label>
    ...
</fast-text-field>
```

**What behavior did you expect?**

Label should be hidden in all browsers.

**In what environment did you see the issue?**

* Browser Mozilla FireFox
* Version 1.8.0

### PR DESCRIPTION
**Pull request by CuddleBunny**
# Description

Moved creation of the proxy element to connectedCallback.

## Motivation & context

Resolves #3741.

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Comment by CuddleBunny** [comment]
@chrisdholt - Sure thing, I will take a look at them.

**Comment by CuddleBunny** [comment]
@chrisdholt - done.

**Comment by EisenbergEffect** [comment]
Definitely want a review on this particular PR from @nicholasrice when he gets the chance.

**Comment by nicholasrice** [comment]
Thanks for looking into this @CuddleBunny. I'm unsure why this fixes the issue; The proxy is appended during the `connectedCallback` of `FormAssociated` and I wouldn't expect changing *when* the proxy is created to affect the `slotted` binding. The proxy is still appended in the default slot when it is appended isn't it? If so, still expect the `slotted` binding to update the observable property and add the hidden class. Is there something I'm missing?

**Comment by nicholasrice** [comment]
A thought I had was that `FormAssociated` could append a `<slot name="proxy"></slot>` to the shadow root and then append the proxy to proxy slot. That would prevent this sort of issue in the future as well. @EisenbergEffect do you have thoughts on that? Would that screw up anything in the templating engine?

**Comment by EisenbergEffect** [comment]
@nicholasrice That's shouldn't break anything. The template engine just does and appendChild on the shadow root. It doesn't remove any nodes that may have been placed there outside of the templating engine's code. The one exception to that is if the element is doing custom rendering, meaning that it doesn't have a template, and then someone dynamically configures a template later, the engine doesn't know any other way to handle this than to clear out the entire shadow root and then append the new template. I don't think that's something that needs to be considered in this case though. Just including that for completeness.

**Comment by CuddleBunny** [comment]
Closing this to create a new PR which takes a new approach.

**Pull request closed without merging**
