### PR TITLE
update component styles to leverage context.tagFor() for nested element styles

### PR DESCRIPTION
**Pull request by chrisdholt**
# Pull Request

## 📖 Description
This PR introduces an update to make styles more portable to other design system prefixes by leveraging the `context.tagFor()` API for stylesheets which reference slotted or nested components.

### 🎫 Issues
None have presented themselves with my testing

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Review by janechu — APPROVED** [review]

**Review by EisenbergEffect — APPROVED** [review]

**Review by robarbms — APPROVED** [review]

**Review by scomea — APPROVED** [review]

**Review by litteredwitherrors — APPROVED** [review]

**Review by radium-v — COMMENTED** [review]
This feels weird, since now if I want to use the `<fast-tooltip>` component on its own, I must have an import dependency on the `AnchoredRegion` from `fast-foundation`. But the tag for `AnchoredRegion` doesn't exist in foundation, it exists in components. Is the `baseName` required to compose the element, or am I missing something else that goes on under the hood?

**Comment by EisenbergEffect** [comment]
There's an improvement coming to enable using the foundation class to look up the tag.

**Comment by chrisdholt** [comment]
> This feels weird, since now if I want to use the `<fast-tooltip>` component on its own, I must have an import dependency on the `AnchoredRegion` from `fast-foundation`. But the tag for `AnchoredRegion` doesn't exist in foundation, it exists in components. Is the `baseName` required to compose the element, or am I missing something else that goes on under the hood?

Base Name is required to compose the element, prefix defaults to fast but can be enumerated. The key here is that our components already support `context.tagFor(AnchoredRegion)` to ensure that `fast-anchored-region` can become `foo-anchored-region` or `bar-anchored-region`. If our styles are explicitly written for `fast-` they will be unusable if someone tries to register with a custom prefix for their project.

The import dependency bit has already started up in conversation where components can register their dependencies here. I think that's an DX and ergonomic improvement. @eisenbergeffect can advise on that status

**Comment by EisenbergEffect** [comment]
Actually, ignore my comment from above. But, yes we're working on a few additional things in this area. The idea of this is to be able to create templates and styles based on components even if we don't know the final name of the component.

**Review by nicholasrice — APPROVED** [review]

**Pull request merged**
