### PR TITLE
fix: remove api-extract exception

### PR DESCRIPTION
**Pull request by Ibrahimmaga**
# Description

## Issue type checklist

- [x] **Chore**: A change that does not impact distributed packages.
- [ ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [x] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by EisenbergEffect — COMMENTED** [review]
I can't recall what the effect of this was. Maybe @radium-v remembers. Let's double check before we remove this.

**Review by Ibrahimmaga — COMMENTED** [review]
Removing it is not even solving the problem. I might needs to reverse the changes. John is also looking into the issue with api-extractor.

**Comment by radium-v** [comment]
I don't think this is actionable yet. API Extractor version 7.8.2 [introduces a change that reports errors on `import()` statements in the generated declaration files](https://github.com/microsoft/rushstack/blob/master/apps/api-extractor/CHANGELOG.md#782), which would need to be resolved before upgrading to a newer version of the extractor.

There's also no indication that the issue tracked by #3317 is fixed on the extractor side, so the warnings still cause failures when running `api-extractor` without the `--local` flag.

**Comment by Ibrahimmaga** [comment]
This PR is not solving the issue of api extractor

**Pull request closed without merging**
