### PR TITLE
Fix a typo in the documentation

### PR DESCRIPTION
**Pull request by norival**
# Pull Request

## 📖 Description

Just fixing a typo in the doc :)

### 🎫 Issues

None.

## 👩‍💻 Reviewer Notes

Just fixing a typo in the doc :)

## 📑 Test Plan

None

### General

- [ ] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by scomea — APPROVED** [review]

**Review by awentzel — APPROVED** [review]

**Review by janechu — APPROVED** [review]

**Review by EisenbergEffect — APPROVED** [review]

**Comment by nicholasrice** [comment]
@norival would you mind running `yarn change` from the package root and selecting type: none?

Thanks!

**Comment by norival** [comment]
> @norival would you mind running `yarn change` from the package root and selecting type: none?
> 
> Thanks!

I did this, but it is not generating any change file :

image

Am I doing something wrong?

**Comment by nicholasrice** [comment]
Interesting. @awentzel @Ibrahimmaga @chrisdholt Are there any known issues w/ Beachball and PRs from a fork?

**Comment by chrisdholt** [comment]
> Interesting. @awentzel @Ibrahimmaga @chrisdholt Are there any known issues w/ Beachball and PRs from a fork?

I run off forks in other repos regularly. Maybe there’s a bug? I’d try targeting the branch and “origin” using the method in the contributing docs.

**Review by chrisdholt — APPROVED** [review]

**Review by Ibrahimmaga — APPROVED** [review]

**Comment by Ibrahimmaga** [comment]
I pulled down your branch and I run yarn change. It was working and giving me the option to create a change file. Please try again, let me know if it doesn't work.

**Comment by chrisdholt** [comment]
> I pulled down your branch and I run yarn change. It was working and giving me the option to create a change file. Please try again, let me know if it doesn't work.

As a follow-up here, be sure you're running at the root of the repo!

**Comment by litteredwitherrors** [comment]
> I pulled down your branch and I run yarn change. It was working and giving me the option to create a change file. Please try again, let me know if it doesn't work.

FWIW, I did the same and it worked for me as well.

**Comment by norival** [comment]
Ok, it worked this time. I don't know what was wrong last time. Thanks :)

**Comment by chrisdholt** [comment]
> Ok, it worked this time. I don't know what was wrong last time. Thanks :)

Fantastic! I’m watching the build and we’ll get it in!

**Pull request merged**
