### PR TITLE
Handle keyboard navigation with changing focusable elements in the toolbar

### LINKED ISSUE #5723: fix: keyboard navigation in toolbar with disabled buttons
# 🐛 Bug Report

When using the keyboard to navigate through a toolbar, the focus gets "lost" when encountering a disabled button.

## 💻 Repro or Code Sample

1. Navigate to https://explore.fast.design/components/fast-toolbar and update the code to be
```
<fast-toolbar>
    <fast-button>button1</fast-button>
    <fast-button>button2</fast-button>
    <fast-button disabled>button3</fast-button>
    <fast-button>button4</fast-button>
</fast-toolbar>
```

2. Click on the toolbar (but not one of the buttons). 'button1' has focus (correct).
3. Press the right arrow on the keyboard. 'button2' has focus (correct).
4. Press the right arrow a second time on the keyboard. Nothing in the toolbar has focus (incorrect - focus should have moved to 'button4')
5. Click on the toolbar again (still not one of the buttons). 'button1' has focus again.
6. Press the right arrow on the keyboard. 'button4' has focus (incorrect - focus should have moved to 'button2' as in step 3 above).

## 🤔 Expected Behavior

With the toolbar in focus, pressing the right arrow key on the keyboard should move focus to the next element in the toolbar, skipping over any disabled buttons.

## 😯 Current Behavior

With the toolbar in focus, pressing the right arrow key on the keyboard moves focus to the next element in the toolbar until the next element is a disabled button. The toolbar attempts to focus the disabled button, which does not work. After this, pressing the arrow keys in the toolbar does nothing.

## 💁 Possible Solution

I'm willing to contribute a fix, but I don't have a specific fix in mind yet. I believe the fix should go in `reduceFocusableItems` of [toolbar.ts](https://github.com/microsoft/fast/blob/9542f92e85384aa39e8b9ab71b3972fb6dfc5bcd/packages/web-components/fast-foundation/src/toolbar/toolbar.ts#L243). That function incorrectly identifies the disabled button as a focusable element because `isFocusableFastElement` is true since `delegatesFocus` is set to `true` on the button.

## 🔦 Context

This keeps toolbars in my application from being fully keyboard accessible.

## 🌍 Your Environment

* OS & Device: Windows 10 PC
* Browser: Chrome
* Version 99.0.4844.51

### PR DESCRIPTION
**Pull request by mollykreis**
# Pull Request

## 📖 Description

Resolves #5723
Keyboard navigation in the toolbar did not correctly handle disabled buttons or elements in the toolbar becoming hidden or disabled after they were slotted within the toolbar. With this change, the toolbar monitors the children and correctly evaluates whether each is focusable. If the set of focusable elements changes, the currently focused element in the toolbar remains focused as long as it is still focusable.

### 🎫 Issues

Resolves #5723

## 📑 Test Plan

I added a number of additional toolbar unit tests for keyboard navigation with hidden & disabled items.

### General

- [x] I have included a change request file using `$ yarn change`
- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Assigning to @radium-v for review and resolution.

**Comment by radium-v** [comment]
Now that we're essentially checking for any changes to the elements regardless of slot, the `children()` template directive may be better for handling this scenario.

@mollykreis I created a branch here to test it out: https://github.com/microsoft/fast/tree/users/jokreitl/nonfocusable-items-in-toolbar

**Comment by mollykreis** [comment]
Converting to a draft PR while I try to resolve the merge issues.

**Comment by mollykreis** [comment]
@radium-v, is there anything else you are waiting on from me before this can be merged?

**Review by chrisdholt — APPROVED** [review]
This looks good to me - @radium-v is also going to take a final pass to ensure we're good. Thanks @mollykreis for this and your patience :)

**Pull request merged**
