### PR TITLE
feat(foundation): eagerly register integrated custom elements

### PR DESCRIPTION
**Pull request by yinonov**
side effect will register integrated components

# Pull Request

### General

- [ ] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Comment by yinonov** [comment]
@KingOfTac I know we said it's out of scope for `tagFor` but is that the direction?

**Comment by KingOfTac** [comment]
Hmmm. Not sure this is the best approach. I like the idea behind it, but introducing side effects to `tagFor` is probably not the right way to go about it. There is also the question of how does one go about passing options to `define` here? What happens when someone is importing a dependency's definition separately in order to customize the component, only to find that it is already defined?

This does give me an idea of a way we could enable components to define their dependencies while also still accounting for these other scenarios, I just need a little time to gather my thoughts and test it out.

**Comment by yinonov** [comment]
> Hmmm. Not sure this is the best approach. I like the idea behind it, but introducing side effects to `tagFor` is probably not the right way to go about it. There is also the question of how does one go about passing options to `define` here? What happens when someone is importing a dependency's definition separately in order to customize the component, only to find that it is already defined?
> 
> This does give me an idea of a way we could enable components to define their dependencies while also still accounting for these other scenarios, I just need a little time to gather my thoughts and test it out.

thanks! I think it is a great deal of an issue, been struggling with it in scoped elements implementation as well.

**Comment by KingOfTac** [comment]
Would also like to see if @EisenbergEffect @chrisdholt @nicholasrice have any thoughts/ideas here since it has come up a few times in the past. Ideally I'd like to make sure if there are any plans for the future to enable something like this, that we are working towards that goal instead of against it.

**Comment by yinonov** [comment]
It seems that supporting the `options` member of a component definition is the main blocker for this.
Personally, I never use the `options`. If wanting to customise anything, I simply fork the part needed, whether it's a template or class members. The available options are anyway an opinionated implementation and doesn't necessarily provide all the required infinite world of customisations. Not sure how other consumers feel about this but it might be worth a re-evaluation of the `options` member?

**Comment by yinonov** [comment]
ran into this post today which could be nice for the interim
https://open-wc.org/blog/scoped-elements-without-polyfill/

**Comment by janechu** [comment]
Due to the outstanding draft status of this PR, and the existence of a workaround I'll close this for now.

**Pull request closed without merging**
