### PR TITLE
Add missing whitespace

### PR DESCRIPTION
**Pull request by jlecordier**
# Pull Request

## 📖 Description

Added a missing whitespace to follow the formatting of the rest

### General

- [ ] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Review by robarbms — APPROVED** [review]

**Review by radium-v — APPROVED** [review]

**Review by chrisdholt — APPROVED** [review]

**Review by eljefe223 — APPROVED** [review]

**Review by EisenbergEffect — APPROVED** [review]

**Comment by EisenbergEffect** [comment]
@jlecordier Can you add a change file to this PR? Just run `yarn change` from the root of the repo.

**Comment by jlecordier** [comment]
> @jlecordier Can you add a change file to this PR? Just run `yarn change` from the root of the repo.

Hi, I've tried to, but from `npm i` I had dependencies conflicts (so I ran `npm i --force`), and when trying to run `yarn change`, I had multiple errors concerning tests 🤷‍♂️ I would be happy to get some help but I think it would be a better idea that you do it directly yourselves

**Comment by EisenbergEffect** [comment]
Strange. Thanks for letting me know. We'll have a look into it and get back to you.

**Comment by awentzel** [comment]
@jlecordier @EisenbergEffect I ran `yarn change`, updated it as a patch, rebased, and pushed.  It should be ready to go, but may still require @jlecordier to sign the CLI via the warning above.

**Comment by jlecordier** [comment]
> @jlecordier @EisenbergEffect I ran `yarn change`, updated it as a patch, rebased, and pushed. It should be ready to go, but may still require @jlecordier to sign the CLI via the warning above.

Thanks for your help. Do you have any idea on why I ran into issues ? So I can learn from it and be autonomous next time

**Pull request merged**
