### PR TITLE
feat: add string literal union types to component attributes that use option enums

### LINKED ISSUE #5494: feat: export component option enums as string literal union types
# 🙋 Feature Request

Continuing a conversation from [this thread](https://github.com/microsoft/fast/issues/5387).

**Background:**

Currently, there are a number of fast foundation component attribute value types that are defined with enums (i.e. [TextFieldTypes](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/text-field/text-field.options.ts), [SelectPosition](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/select/select.options.ts), and so on). 

This is a non-issue when creating/using new web components based on these foundation components, however, once the new components are wrapped with `fast-react-wrapper` and used within a React application you will run into TS errors/issues along these lines:

```jsx
// This does NOT work (i.e. TS Error: Type '"password"' is not assignable to type 'TextFieldType | undefined'.)
// TypeScript is looking for the enum type and will not allow a literal string value
<VSCodeTextField type="password"></VSCodeTextField>
```

An easy solution is to import/export these enums so they are consumable by downstream component libraries––however, this would result in what I think is a clunky/unintuitive developer experience:

```jsx
// This works but is a bit clunky imo
import {TextFieldTypes} from "toolkit";
<VSCodeTextField type={TextFieldTypes.password}></VSCodeTextField>
```

As I explain more below, I think the ideal solution is to export or even convert these enums into string literal union types.

## 🤔 Expected Behavior

You should be able to write out the literal string value of any attribute without running into type errors.

## 😯 Current Behavior

FAST Foundation component attributes which are defined with enums and then wrapped as React components must import and use the enums to avoid type errors.

## 💁 Possible Solution

After a quick peek through the fast foundation source code it actually looks like most (if not all) of these enums are exported and thus a very easy solution would be for consumers of the foundation components to simply re-export these enums in their own component libraries for end-users to use.

With that said, I would ideally love to see FAST Foundation components provide or even convert instances of these attribute enums into string literal union types so that there is still type safety/restrictions, but end-users can simply type out the literal value versus being forced to import and use the enums.

For example:

```typescript
// Instead of this
export enum TextFieldType {
    email = "email",
    password = "password",
    tel = "tel",
    text = "text",
    url = "url",
}

// Create and use this
export type TextFieldType = "email" | "password" | "tel" | "text" | "url";
```

In the above-mentioned thread @EisenbergEffect also left the following comment:

> ...Maybe we can provide some sort of typing that enables using either the enum or the string literal? Basically, I want to see if we can avoid a breaking change...

As of TypeScript `v4.1` it should actually be possible to convert the enums into string literal unions with template syntax (this way there is one source of truth for the typings):

[StackOverflow Reference](https://stackoverflow.com/questions/52393730/typescript-string-literal-union-type-from-enum/59496175)
```typescript
export enum TextFieldType {
    email = "email",
    password = "password",
    tel = "tel",
    text = "text",
    url = "url",
}

export type TextFieldLiteralType = `${TextFieldType}`;
```

From here both the enum and string literal union can theoretically be exported and used by consumers. With that said, **_I believe the really important part of ensuring that the string literal union type solution works is to update the foundation component type declarations_**. 

For example, the [text field `type` attribute](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/text-field/text-field.ts#L72-L85) should be updated to look something like so:

```typescript
import { TextFieldType, TextFieldLiteralType } from "./text-field.options"; // <-- import both enum and string literal union type

/**
 * Allows setting a type or mode of text.
 * @public
 * @remarks
 * HTML Attribute: type
 */
@attr
public type: TextFieldType | TextFieldLiteralType = TextFieldType.text; // <-- Note the new type annotation
private typeChanged(): void {
    if (this.proxy instanceof HTMLInputElement) {
        this.proxy.type = this.type;
        this.validate();
    }
}
```

I have yet to test this, but I believe (??) this should ensure backward compatibility while also giving end-users the option to simply type out the literal values if they desire.

## 🔦 Context

We're planning on publishing a set of wrapped React components for the Webview UI Toolkit for VS Code and would ideally like an easy developer experience for toolkit consumers that does not require importing enums for various component attributes.

### PR DESCRIPTION
**Pull request by hawkticehurst**
# Pull Request

## 📖 Description

This PR adds inline string literal union types to all foundation components that use an enum for attribute options. This should fix an issue where downstream React-wrapped component libraries built with `fast-foundation` are forced to expose these enums for users to consume and use when defining a handful of attribute values.

For example, this currently does not work:

```ts
// This does NOT work (i.e. TS Error: Type '"password"' is not assignable to type 'TextFieldType | undefined'.)
// TypeScript is looking for the enum type and will not allow a literal string value
<VSCodeTextField type="password"></VSCodeTextField>
```

Instead, the attribute value must be defined with an enum:

```ts
import {TextFieldTypes} from "toolkit";
<VSCodeTextField type={TextFieldTypes.password}></VSCodeTextField>
```

This PR updates attribute type annotations so that both examples shown above are valid.

### 🎫 Issues

This pull request resolves #5494

## 👩‍💻 Reviewer Notes

I'm currently opening this as a draft PR in order to get some initial feedback before wrapping up the PR. In particular, I'd love feedback on:

- **_Whether these string literal types should be inlined on attribute definitions or abstracted into a type alias like discussed in #5494?_**

   The reason I opted to have these types be inline is that it will result in much better intellisense for downstream users of the components versus the abstracted type. As an example:

   With inline types I can quickly grep what the available options for a given attribute are (i.e. "above" and "below"):
   Screen Shot 2022-03-15 at 2 02 58 PM

   If the literal types are abstracted into a type alias then component users will have to either dive deeper into the type information and/or look at the component documentation to discover what's allowed.
   Screen Shot 2022-03-15 at 2 03 58 PM

   With all this said I can see there being arguments in favor of using a type alias (such as maintainability in the cases where these string literal unions are used in more than one place). So I would love feedback on what direction you would like to go as maintainers.

- **_Since this PR only changes type annotations, how should I go about testing this beyond making sure everything still builds correctly?_**

   I have my own plans to create a local build from these changes and copy-pasta the build dir into a sample React application that confirms these changes have been fixed with the toolkit React components. I'm happy to share this sample with all of you to review.

   Beyond that, however, I'm wondering if there's a preferred method of testing this that you would like to see?

-  _**I've also had some async discussions with @chrisdholt about this PR that are worth discussing as well.**_

   In particular, there were thoughts about whether enums should just be deprecated at this point or not. I think we casually landed on the answer being no, but open to hearing more thoughts.

   Also if we don't deprecate enums, might there be a way to simplify the overall type annotations so that the string literal union accepts the enum as part of the union? (I'm sure I've butchered what you were thinking of for this idea so please feel free to correct me @chrisdholt).

## 📑 Test Plan

_Reference above question about testing strategy._

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## ⏭ Next Steps

Once the above questions are answered and we align on a direction for how this should be implemented/what to implement I'll finish up this work and add commits such as the change request.

### CODE REVIEW

**Comment by nicholasrice** [comment]
Thanks @hawkticehurst! A few thoughts the discussion points you brought up:

**Inline vs Abstracted Type Unions**
I think the ease of usability of the inlined types makes me prefer that approach. If folks need to *reference* the type, they can always use `ElementCtor['propertyName']` as the type reference or the enum if we decide to keep it.

**Deprecate Enums**
My first instinct was to deprecate so that we don't need to keep both synchronized, but I'm curious what ya'll discussed that made you prefer keeping them.

Overall this looks great, thanks for putting it up!

**Comment by hawkticehurst** [comment]
> Thanks @hawkticehurst! A few thoughts the discussion points you brought up:
> 
> **Inline vs Abstracted Type Unions** I think the ease of usability of the inlined types makes me prefer that approach. If folks need to _reference_ the type, they can always use `ElementCtor['propertyName']` as the type reference or the enum if we decide to keep it.
> 
> **Deprecate Enums** My first instinct was to deprecate so that we don't need to keep both synchronized, but I'm curious what ya'll discussed that made you prefer keeping them.
> 
> Overall this looks great, thanks for putting it up!

Thanks for the input @nicholasrice!

As I look back at my conversation with @chrisdholt it looks like the major concern was just around whether removing enums would cause a breaking change anywhere. 

For example, this will definitely cause a breaking change in the toolkit, however, I'm _slightly_ less concerned about this because we're still pre-1.0 so there's some flexibility to make this kind of change. 

The other point of consideration is that these enums are used a lot within FAST Foundation as an implementation detail (on top of being used for type annotations).

```ts
// Example of the ComboboxAutocomplete enum being used as an implementation detail
private get isAutocompleteInline(): boolean {
    return (
        this.autocomplete === ComboboxAutocomplete.inline || this.isAutocompleteBoth
    );
}

private get isAutocompleteList(): boolean {
    return this.autocomplete === ComboboxAutocomplete.list || this.isAutocompleteBoth;
}

private get isAutocompleteBoth(): boolean {
    return this.autocomplete === ComboboxAutocomplete.both;
}
```

Obviously, these can all be changed to literal string values but depending on your opinions as maintainers there could be an argument that using literal strings is more brittle/error-prone than using enums.

Finally, I think the last consideration was just around timing. We're tentatively hoping to release v1.0 of the toolkit on April 4th so keeping this PR scoped to just adding inline literal types and not touching the enums at this time makes it a bit easier to get this work merged.

**Comment by nicholasrice** [comment]
@hawkticehurst I see, thanks for catching me up there. *Removing* the enums would certainly be a breaking change, but marking them deprecated could happen w/o any changes to code or exports. I'll propose moving the enum deprecation discussion to a separate issue that we can follow up on. That will unblock *this* PR and also give the community more opportunity to comment on the usefulness of the enums. Does that sound suitable?

**Comment by hawkticehurst** [comment]
> @hawkticehurst I see, thanks for catching me up there. _Removing_ the enums would certainly be a breaking change, but marking them deprecated could happen w/o any changes to code or exports. I'll propose moving the enum deprecation discussion to a separate issue that we can follow up on. That will unblock _this_ PR and also give the community more opportunity to comment on the usefulness of the enums. Does that sound suitable?

Ahhh omg 🤦🏻‍♂️

I was totally conflating deprecation with removal this entire time. Yes, in that case, moving the deprecation conversation to a different PR sounds perfect. Thanks for clarifying

**Comment by hawkticehurst** [comment]
Okay, I was able to [create a small demo](https://github.com/hawkticehurst/fast-string-literal-union-demo) that tests if these changes work in the Webview UI Toolkit (they do 🥳). Feel free to check it out and follow the directions in the README to validate the changes for yourself.

I also regenerated the API extractor report file, ran `yarn change`, and merged in the latest changes from main.

Beyond the lingering question about whether further testing strategies are preferred, I'm opening this up for a proper review!

**Review by chrisdholt — APPROVED** [review]

**Pull request merged**
