### PR TITLE
chore: convert configuration files to html

### PR DESCRIPTION
**Pull request by janechu**
# Description

This converts the config files into `HTML` format, each components will have a folder called "scenarios".

The structure requires the following:
- Each scenario will be denoted its place in the select dropdown by the number in the file name (eg. `scenario.1.html` comes before `scenario.2.html`).
- The name of the option is recorded as a string between inline comments `<!-- scenario-title:start -->` and `<!-- scenario-title:end -->`.
- The contents of the scenario, which will choose a root tree item from the first item it comes across, will be selected between the inline comments `<!-- scenario:start -->` and `<!-- scenario:end -->`.

## Motivation & context

Begins to solve #3930

## Issue type checklist

- [x] **Chore**: A change that does not impact distributed packages.
- [ ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Comment by nicholasrice** [comment]
@janchu what is the reason that you chose to use HTML comments to define the title and scenario start / end? It strikes me that there may be some easier ways to parse this information out that doesn't rely on functional comments (full transparency, I'm not a big fan of code comments that do things):
1. Use the title attribute on the scenario element
2. Use a `<template>` element to define the scenario

for example:

```html
// my-scenario.1.html
<template title="My Scenario">
  <fast-anchor>I'm an anchor!</fast-anchor>
</template>
```

**Comment by nicholasrice** [comment]
Another thought on the above, if we went with the  template element approach you probably wouldn't need multiple HTML files for each component.

**Comment by janechu** [comment]
@nicholasrice sure, I initially had this as a single file but I thought it would be easier to visually parse changes with one scenario per file. I can change that to a single file. I can make the other change to use `<template>` as well, I was avoiding having anything functional other than the actual HTML for the scenario (hence the use of comments) in these HTML files that would be used for parsing but I can see that the `<template>` could make sense here, and less prone to parsing issues.

**Comment by nicholasrice** [comment]
Cool yea, single-file was just a thought I had that might be easier with `<template>` but I'm also happy with multiple files; whatever makes sense.

**Review by nicholasrice — APPROVED** [review]

**Review by scomea — APPROVED** [review]

**Review by EisenbergEffect — APPROVED** [review]

**Comment by EisenbergEffect** [comment]
I like how this turned out in the end. Very nice 😄

**Pull request merged**
