### PR TITLE
fix: data-grid stores generated templates

### PR DESCRIPTION
**Pull request by scomea**
# Description
Store the templates to avoid creation functions being called more than once

## Motivation & context
Avoid creating unneccessary template instances.

## Issue type checklist
- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [x] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by EisenbergEffect — APPROVED** [review]
@scomea Technically, this change isn't needed because the decorator will run once and cache the created instance. The place where it tends to matter is when a template is used inside of another template. In that case you don't want to create the template within the template because every time the parent template is instantiated the child template will get re-defined. So, in that case you want to factor it out and re-use it. Let me know if this makes sense.

Nothing wrong with this refactor of course. But wanted to let you know that it wasn't technically needed.

**Comment by scomea** [comment]
@EisenbergEffect Good to know.  I'm thinking the easiest general approach is to prefer passing the template unless there is a specific reason to pass the function.

**Comment by scomea** [comment]
@EisenbergEffect I think the row/cell commit I added fits the template within a template scenario?

**Comment by EisenbergEffect** [comment]
Yes. Definitely. That second set of updates is the scenario where it matters. Spot on.

**Review by chrisdholt — APPROVED** [review]

**Review by SethDonohue — APPROVED** [review]

**Review by robarbms — APPROVED** [review]

**Pull request merged**
