### PR TITLE
Export design-system-provider from fast-components

### PR DESCRIPTION
**Pull request by nicholasrice**
# Pull Request

## 📖 Description
This change exports the DesignSystemProvider base class from `@microsoft/fast-components` so that it can be extended by experience authors.

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Review by chrisdholt — APPROVED** [review]

**Comment by ben-girardet** [comment]
I'm wondering if the `@designToken` decorator should also be exported ? Seems like a nice utility to set a design token from a DSP attribute ?

**Comment by nicholasrice** [comment]
@ben-girardet yea I don't see an issue with that - let me make it a bit more generic and I can add it to the exports.

**Comment by nicholasrice** [comment]
@ben-girardet I'm going to take that as a follow-up; I'm not sure I want to ship the existing implementation cause it could cause unintuitive bugs if folks don't know the implementation details of the decorators. I want to find a more robust solution.

Tracking the request here: https://github.com/microsoft/fast/issues/4916

**Comment by ben-girardet** [comment]
It makes total sense 👍🏻

**Review by janechu — APPROVED** [review]

**Pull request merged**
