### PR TITLE
fix: add display:grid to flipper slots to prevent container from changing glyph position

### LINKED ISSUE #4497: Inherited font-sizes move glyph positions in fast-flipper
When `<fast-flipper>` is a child of any element with a font-size, the slots inherit the parent font-size which messes up the glyph positioning. You can even see it in the docs page: https://www.fast.design/docs/components/flipper/ where it the glyph is offset due to the 15.4px font-size.

**What are the steps to reproduce the issue?**
- Go to the [example codepen](https://codepen.io/brookdurant/pen/vYgNEKa)
- Anywhere `<fast-flipper>` or `<fluent-flipper>` are children of elements that have a font-size and don't have a font-size explicitly set on themselves

**What behavior did you expect?**

I would expect default flipper behavior to be **either**: 
- the flipper to be unaffected by parent `font-size` (preferable)
- the entire flipper and its children to resize based on inherited `font-size`

**If applicable, provide screenshots:**
flipperError

**Is there any additional context?**
I think the flipper behavior is different that the button behavior. Should they be consistent?

One option for fix could be setting `font-size: 0;` on the flipper by default.

### PR DESCRIPTION
**Pull request by brookdozer**
# Description
Set `font-size:0` in flipper.styles.ts for the `.next` and `.previous` slot classes so the glyphs will render in their proper positions regardless of container's inheritable font-size

## Motivation & context
Fixes #4497 

## Issue type checklist
- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Comment by scomea** [comment]
Wouldn't it be weird if someone adds content to a slot and we apply font size 0?  Can we specify the height of something instead?

**Comment by chrisdholt** [comment]
> Wouldn't it be weird if someone adds content to a slot and we apply font size 0? Can we specify the height of something instead?

This is a good call out if someone wanted to pass localized text. What if we applied the font size to slotted SVG’s?

‘’’css
::slotted(SVG) {
    font-size: 0;
    line-height: 0;
}
’’’

**Comment by brookdozer** [comment]
Great comments, @scomea and @chrisdholt, I think we should move discussion to the bug, #4497. The `::slotted(svg) {}` won't work because the flipper content isn't always slotted.

**Review by radium-v — CHANGES_REQUESTED** [review]
Setting a `display` value on `.previous` and `.next`, or on slotted `svg`s would be better and more intuitive than resetting the `font-size`/`line-height`.

**Review by radium-v — APPROVED** [review]

**Review by scomea — APPROVED** [review]

**Review by EisenbergEffect — APPROVED** [review]

**Comment by EisenbergEffect** [comment]
@bheston See the comment in the PR above. I've noticed a number of similar comments in other components. How far are we from having the adaptive typography worked out enough to start resolving these "todos"?

**Pull request merged**
