### PR TITLE
docs(dialog): clarify the need for z-index #5461

### LINKED ISSUE #5461: docs: clarify the need for z-index on dialogs
# 🙋 Documentation Request

Community members have repeatedly encountered issues using our dialog components where the component does not overlay their UI properly.

## 💁 Possible Solution

We should add content to our documentation on this component that indicates the typical requirement to set z-index.

### PR DESCRIPTION
**Pull request by yinonov**
# Pull Request

## 📖 Description

clarify the need for z-index in dialogs

### 🎫 Issues
Closes #5461 

### General

- [ ] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [x] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Review by EisenbergEffect — APPROVED** [review]

**Review by nicholasrice — APPROVED** [review]

**Review by radium-v — CHANGES_REQUESTED** [review]
@chrisdholt can you confirm if the included change files are correct?

**Review by scomea — APPROVED** [review]

**Comment by yinonov** [comment]
Any chance of moving this forward or a little guidance? It can engage on picking up more issues 🙃

**Comment by chrisdholt** [comment]
> Any chance of moving this forward or a little guidance? It can engage on picking up more issues 🙃

Per @radium-v's note, it's odd that there are a ton of additional change files being added here when only `fast-foundation` is being touched. Can you try and remove any files that aren't the `fast-foundation` change files and let's see how the build looks after that?

**Comment by yinonov** [comment]
Of course, it's odd that it added those in the cli from the first place, the _change_ tool also eagerly commits the changes.

thought it's some repo dedicated voodoo.

I'll fix

**Review by chrisdholt — APPROVED** [review]

**Review by chrisdholt — APPROVED** [review]

**Comment by chrisdholt** [comment]
Thanks for your patience @yinonov, getting this merged now!

**Pull request merged**
