### PR TITLE
feat: upgrade api-extractor version to 7.23.0

### PR DESCRIPTION
**Pull request by williamw2**
# Pull Request

## 📖 Description
Upgrading the @microsoft/api-exctractor version to 7.23.0 in order to support the use of custom JSDoc tag definitions in the tsdoc.json file. This is necessary in order to add slot, CSS parts, and event tags in the fast-foundation component comments so that they can be read by the CEM Analyzer.

Only the api-extractor package version is updated in this PR. All changes to the api-report.md files are strictly a result of changes in the api-extractor between V7.8.1 and V7.23.0.

### 🎫 Issues
Related to #5912 

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Review by chrisdholt — APPROVED** [review]
Thanks @williamw2!

**Review by scomea — APPROVED** [review]

**Review by awentzel — CHANGES_REQUESTED** [review]
Deployment of documentation is failing among other tests.  Please verify documentation by running:
1. yarn
2. cd sites/website
3. yarn && yarn start
If no errors in documentation and all workflows pass I'm happy to approve.  Thanks

**Review by nicholasrice — APPROVED** [review]

**Comment by williamw2** [comment]
> Deployment of documentation is failing among other tests. Please verify documentation by running:
> 
> 1. yarn
> 2. cd sites/website
> 3. yarn && yarn start
>    If no errors in documentation and all workflows pass I'm happy to approve.  Thanks

Yes, it is a problem. I'm able to repro locally and am trying to find a solution.

**Comment by williamw2** [comment]
@awentzel I believe I have resolved this issues. Could you please confirm? Thanks!

**Review by EisenbergEffect — APPROVED** [review]

**Review by awentzel — APPROVED** [review]
Looks like those warnings are still there, but that's because my PR hasn't gone through yet.  The site builds and loads without errors.  Thanks for checking.

**Pull request merged**
