### PR TITLE
fix: update storybook to use custom element definitions and fix rollup

### PR DESCRIPTION
**Pull request by nicholasrice**
# Pull Request

## 📖 Description
This PR updates the Storybook configuration to use component definitions. It updates the `index-rollup.ts` file to export a `DesignSystem` instance that has all components exported by the package registered to it, and the DesignSystem applied to the document body. Importing this side-effect into storybook's preview script causes all components to be defined for the Storybook inner-loop.

This PR also ensures that consumers of `fast-components.min.js` have FAST elements defined when the script is added, which is the desired experience for that script.

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Review by janechu — APPROVED** [review]

**Review by EisenbergEffect — APPROVED** [review]
Awesome! I didn't know you were working on this. Let's get this in ASAP. I have some improvements I need to make to the DesignSystem API and would love to do that as a follow up to this. Marking this one off my list though 😄

**Review by chrisdholt — APPROVED** [review]
Let's go!

**Review by chrisdholt — COMMENTED** [review]
@nicholasrice do you want to add a change file for this describing it?

**Comment by nicholasrice** [comment]
@EisenbergEffect yea I was porting of the DesignSystem to DesignTokens and realized I couldn't boot storybook to validate things were working!

**Comment by EisenbergEffect** [comment]
That's definitely a motivator to get this in 😉

**Pull request merged**
