### PR TITLE
docs(fast-element): sharpen repeat directive

### PR DESCRIPTION
**Pull request by yinonov**
# Pull Request

## 📖 Description

snippet of code is confusing as it misses crucial part for it to function

### General

- [ ] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Comment by scomea** [comment]
I don't think whether or not used views are recycled is dependent on 'positioning' being true.  As I understand it turning off 'positioning' is about foregoing that data being available in the binding context in exchange for saving some cycles but does not change the underlying relationship between the items in the array and the views they are bound to.

**Comment by yinonov** [comment]
> I don't think whether or not used views are recycled is dependent on 'positioning' being true.  As I understand it turning off 'positioning' is about foregoing that data being available in the binding context in exchange for saving some cycles but does not change the underlying relationship between the items in the array and the views they are bound to.  

Sorry it's not stated in description. It is the index that'll fail to render properly. If not really needed, maybe omit the index in exchange with something simpler?

**Comment by scomea** [comment]
Ah, ok.  I misunderstood there was an issues getting 'recycle' to work, not just a detail of the sample.

**Review by scomea — APPROVED** [review]

**Review by nicholasrice — APPROVED** [review]

**Review by chrisdholt — APPROVED** [review]
Thanks @yinonov!

**Pull request merged**
