### PR TITLE
chore: typo in docs

### PR DESCRIPTION
**Pull request by idmyn**
it's => its

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Good catch @idmyn Thank you!

**Comment by idmyn** [comment]
@EisenbergEffect if I spot any more typos would you rather I ammend that commit or add new commits?

Thanks for the project!

**Comment by EisenbergEffect** [comment]
@idmyn We can leave this unmerged until early next week and you can just amend to this if that's easier for you.

**Comment by EisenbergEffect** [comment]
@idmyn Any particular reason why this was closed without merging?

**Comment by idmyn** [comment]
@EisenbergEffect I wasn't aware that I had closed it, and the "Reopen and comment" button is greyed out saying "The idmyn:patch-1 branch has no history in common with microsoft:master" 🤔

**Comment by EisenbergEffect** [comment]
Interesting. Thanks for the new PR!

**Pull request closed without merging**
